#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)

garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
function Gunakan_Bug() {
filename="/etc/xray/.bug_optr"
  clear
  echo "Bug List:"
  # Membaca file baris per baris
  i=1
  while IFS="=" read -r key value; do
    # Menampilkan daftar pilihan
    echo "$i.) $key"
    options["$i"]="$value"  # Menyimpan nilai (value) berdasarkan nomor pilihan
    ((i++))
  done < "$filename"
  
  # Meminta input dari pengguna
  echo -e "\nPilih nomor (1-${i-1}):"
  read -p "Enter choice: " choice
  
  # Mengecek apakah pilihan valid
  if [[ "$choice" -ge 1 && "$choice" -lt "$i" ]]; then
    # Mendapatkan nilai (value) yang dipilih
    selected_value="${options[$choice]}"
    echo "Anda memilih: ${options[$choice]}"
    
    # Jika ingin menggunakan nilai tersebut, misalnya menyimpan dalam variabel 'domain'
    bug="$selected_value"
	else
    bug="$domain"
  fi
}

function Daftar_Account() {
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}     %-23s %-12s${RESET}\n" "$user" "$date"
done
}

function Cek_Config_Trojan {
	clear
banner "CHECK TROJAN ACCOUNT"
    printf "${YELLOW}     %-23s %-12s${RESET}\n" "USERNAME" "EXP DATE" 
	garis_atas
	Daftar_Account
    garis_bawah
    echo -e "${WHITE}${BOLD}"
	read -rp " Input Username   : " user
	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi
	
	if ! grep -qwE "^#! $user" /etc/xray/config.json; then
    echo -e "User $user Tidak Ditemukan!!"
	sleep 1
	check-tro
    exit 1
    else
iplimit=$(cat /etc/kyt/limit/trojan/ip/$user)
Quota1=$(cat /etc/trojan/$user)
Quota=$((Quota1 / 1024 / 1024 / 1024))
uuid=$(grep -E "^},{" "/etc/xray/config.json" |  grep -i '"'"${user}"'"' | cut -d " " -f 2 | cut -d '"' -f 2 | uniq )
exp=$(grep -E "^#! " "/etc/xray/config.json" | grep -i ' '"${user}"' ' | cut -d ' ' -f 3 | uniq )
trojanlink1="trojan://${uuid}@${bug}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink="trojan://${uuid}@${bug}:443?path=/trojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${bug}:80?path=/trojan-ws&security=none&host=${domain}&type=ws#${user}"
fi
}

function Details_Account() {
printf "${WHITE}${BOLD} Remarks      : ${user}${RESET}\n"
printf "${WHITE}${BOLD} Host/IP      : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota   : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} User Ip      : ${iplimit} IP${RESET}\n"
printf "${WHITE}${BOLD} Port NTLS    : 443-900${RESET}\n"
printf "${WHITE}${BOLD} port WS      : 80,8880,8080${RESET}\n"
printf "${WHITE}${BOLD} Key          : ${uuid}${RESET}\n"
printf "${WHITE}${BOLD} ISP          : $ISP${RESET}\n"
printf "${WHITE}${BOLD} Path         : /trojan-ws${RESET}\n"
printf "${WHITE}${BOLD} ServiceName  : trojan-grpc${RESET}\n"
}

function Link_Json() {
garis
printf "${WHITE}${BOLD} Link TLS     : ${trojanlink}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link NTLS    : ${trojanlink2}${RESET}\n"
garis 
printf "${WHITE}${BOLD} Link GRPC    : ${trojanlink1}${RESET}\n"
garis
printf "${WHITE}${BOLD} OpenClash    : https://${domain}:81/trojan-$user.txt${RESET}\n"
}

function Details_Expiry() {
garis
echo -e " ${YELLOW} Expiry in   : $exp ${RESET} "
}

Gunakan_Bug
clear
Cek_Config_Trojan
clear
banner "CHECK TROJAN ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"