#!/bin/bash

source /usr/bin/ui.sh

# COLOR VALIDATION
clear
gray="${GRAY}"
YELL='${YELLOW}'
BGX="${BGREEN}"
UPDATE="https://abc.xcodehoster.com/"
BOT="https://abc.xcodehoster.com/"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
   echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${RESET}"
    echo -e "   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    echo -e "     ${YELLOW}Buy access permissions for scripts${RESET}"
    echo -e "             ${YELLOW}Contact Admin :${RESET}"
    echo -e "      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    exit
  fi
}
checking_sc

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e " ${WHITE}${BOLD}                      MENU BOT                ${RESET}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "  ${grenbo}[1]${RESET}${YELL} Add Bot Notifikasi${RESET}"
echo -e "  ${grenbo}[2]${RESET}${YELL} Delete Bot Notifikasi${RESET}"
echo -e "  ${grenbo}[0]${RESET}${YELL} Back To Menu${RESET}"
echo -e ""
read -p "  Select From Options [ 1 - 2 or 0 ] : " menu
case $menu in
1) clear ;
    add-bot-notif
    ;;
2) clear ;
    del-bot-notif
    ;;
0) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac