#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

function Daftar_Account() {
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}     %-23s %-12s${RESET}\n" "$user" "$date"
done

}
	clear
banner "DELETE TROJAN ACCOUNT"
    printf "${YELLOW}     %-23s %-12s${RESET}\n" "USERNAME" "EXP DATE" 
	garis_atas
	Daftar_Account
    garis_bawah
    echo ""
	read -rp " Input Username    : " user
	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi
	if ! grep -qwE "^#! $user" /etc/xray/config.json; then
    echo -e "User $user Tidak Ditemukan!!"
	sleep 1
	m-xray
    exit 1
    else
    uuid=$(grep -wE "$user" "/etc/xray/config.json" | cut -d '"' -f 4 | tail -n1)
    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    sed -i "/^#! $user $exp/,/^},{/d" /etc/xray/config.json
    echo "#! $user $uuid" >> /etc/xray/.userall.db
	sed -i "/^### $user $exp/,/^},{/d" /etc/trojan/.trojan.db
    rm -rf /etc/trojan/$user
    rm -rf /etc/kyt/limit/trojan/ip
	rm -rf /var/www/html/trojan-$user.txt
    systemctl restart xray > /dev/null 2>&1
    clear
banner "DELETE TROJAN ACCOUNT"
    garis_atas
    echo -e "${WHITE}${BOLD}    Client Name : $user ${RESET}"
    echo -e "${WHITE}${BOLD}    Expired On  : $exp  ${RESET}"
    garis_bawah
banner "SCRIPT BY $nama"
    fi
