#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear

banner "MEMBER SSH"
printf "  ${YELLOW}%-18s %-16s  %2s${RESET}\n" "USERNAME" "EXP DATE" "STATUS"
garis
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "  %-17s %-17s %2s\n" "$AKUN" "$exp" "LOCKED"
else
printf "  %-17s %-17s %2s\n" "$AKUN" "$exp" "UNLOCKED"
fi
fi
done < /etc/passwd
garis
banner "SCRIPT BY $nama"
echo ""
read -p "Username atau 'exit' untuk kembali: " user
if [ "$user" == "exit" ]; then
    m-ssh
    exit
fi

if ! getent passwd "$user" >/dev/null 2>&1 || [ -z "$user" ]; then
    echo -e "Failure: User $user tidak ditemukan."
    sleep 1
    del-ssh
else
    userdel "$user" >/dev/null 2>&1
    sed -i "/^$user:/d" /etc/group
    exp=$(grep -w "^#ssh# $user" "/etc/ssh/.ssh.db" | awk '{print $3}' | sort -u)
    grep -wE "^#ssh# $user" "/etc/ssh/.ssh.db" | awk '{print $1" "$2" "$3}' | sort -u | tail -1 >> /etc/xray/.userall.db
    sed -i "/^#ssh# $user/d" /etc/ssh/.ssh.db
    rm -f "/etc/ssh/$user"
    rm -f "/etc/kyt/limit/ssh/ip/${user}"
    rm -f "/var/www/html/ssh-$user.txt"

    echo -e "User $user berhasil dihapus."
    sleep 2
    m-ssh
fi