#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

clear
hariini=`date +%d-%m-%Y`
banner "DELETE EXPIRED ACCOUNT"
garis_atas
printf "${YELLOW}   %-17s %-14s %2s${RESET}\n" "USERNAME" "EXP DATE" "DELETE DATE"
garis_bawah
garis_atas
cat /etc/shadow | cut -d: -f1,8 | sed /:$/d > /tmp/expirelist.txt
totalaccounts=`cat /tmp/expirelist.txt | wc -l`
for((i=1; i<=$totalaccounts; i++))
do
tuserval=`head -n $i /tmp/expirelist.txt | tail -n 1`
username=`echo $tuserval | cut -f1 -d:`
userexp=`echo $tuserval | cut -f2 -d:`
userexpireinseconds=$(($userexp * 86400 ))
tglexp=`date -d @$userexpireinseconds`             
tgl=`echo $tglexp |awk -F" " '{print $3}'`
while [ ${#tgl} -lt 2 ]
do
tgl="0"$tgl
done
while [ ${#username} -lt 15 ]
do
user=$username
username=$username" " 
done
bulantahun=`echo $tglexp |awk -F" " '{print $2,$6}'`
echo "echo "Expired- User : $username Expire at : $tgl $bulantahun"" >> /usr/local/bin/alluser
todaystime=`date +%s`
if [ $userexpireinseconds -ge $todaystime ] ;
then
:
else
echo "Expired- Username : $username are expired at: $tgl $bulantahun and removed : $hariini " >> /usr/local/bin/deleteduser
 printf "${WHITE}${BOLD}   %-13s %-17s %2s${RESET}\n" "$username" "$tgl $bulantahun" "$hariini"
userdel $username
grep -wE "^#ssh# $username" "/etc/ssh/.ssh.db" | awk '{print $1" "$2" "$3}' >> /etc/xray/.userall.db
grep -wE "^#ssh# $user" "/etc/ssh/.ssh.db" | awk '{print $1" "$2" "$3}' | sort | uniq | tail -1 >> /etc/xray/.userall.db
sed -i "/^#ssh# $user/d" /etc/ssh/.ssh.db
rm -f /etc/ssh/$user
rm -f /etc/kyt/limit/ssh/ip/${user}
rm -f /var/www/html/ssh-$user.txt
fi
done
garis_bawah
banner "SCRIPT BY $nama"