#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear

banner "CHANGE MEMBER SSH"
printf "  ${YELLOW}%-18s %-16s  %2s${RESET}\n" "USERNAME" "EXP DATE" "STATUS"
garis
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
printf "  %-17s %-17s %2s\n" "$AKUN" "$exp" "LOCKED"
else
printf "  %-17s %-17s %2s\n" "$AKUN" "$exp" "UNLOCKED"
fi
fi
done < /etc/passwd
garis
center "$(print_rainbow "Masukan Usernamenya")"
garis  
read -p "Input Username: " user

# Cek apakah username kosong atau tidak ada dalam passwd
if [ -z "$user" ] || ! getent passwd "$user" > /dev/null 2>&1; then
  clear
  garis
  center "$(print_rainbow "[ Ubah Batas IP SSH ]")"
  garis  
  echo -e ""
  center "$(printf "${RED}AKUN TIDAK DITEMUKAN !!!${RESET}")"
  echo -e ""
  garis
  echo -e ""
  read -n 1 -s -r -p "Press any key to back"
  m-ssh
  exit 1
fi

# File limit IP untuk user
limit_file="/etc/kyt/limit/ssh/ip/${user}"

if [ -e "$limit_file" ]; then
  current_iplimit=$(cat "$limit_file")

  clear
  garis
  center "$(print_rainbow "[ Ubah Batas IP SSH ]")"
  garis  
  echo -e ""
  center "$(printf "${CYAN}Sebelum Perubahan${RESET}")"
  echo -e ""
  center "$(printf "${YELLOW}Username  : $user${RESET}")"
  center "$(printf "${YELLOW}IP Limit  : $current_iplimit${RESET}")"
  echo -e ""
  garis  
  echo -e ""
  
  read -p "Input IP Baru: " new_iplimit
  if [ -z "$new_iplimit" ]; then
    clear
    garis
    center "$(print_rainbow "[ Ubah Batas IP SSH ]")"
    garis  
    echo -e ""
    center "$(printf "${RED}IP Tidak Valid !!!${RESET}")"
    echo -e ""
    garis
    echo -e ""
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
    exit 1
  else
    echo "$new_iplimit" > "$limit_file"
    clear
    garis
    center "$(print_rainbow "[ Ubah Batas IP SSH ]")"
    garis  
    echo -e ""
    center "$(printf "${GREEN}Perubahan Berhasil!${RESET}")"
    echo -e ""
    center "$(printf "${CYAN}Setelah Perubahan${RESET}")"
    echo -e ""
    center "$(printf "${YELLOW}Username  : $user${RESET}")"
    center "$(printf "${YELLOW}IP Baru   : $new_iplimit${RESET}")"
    echo -e ""
    garis
banner "SCRIPT BY $nama"
  fi
else
  clear
  garis
  center "$(print_rainbow "[ Ubah Batas IP SSH ]")"
  garis  
  echo -e ""
  center "$(printf "${RED}LIMIT IP TIDAK DITEMUKAN !!!${RESET}")"
  echo -e ""
  garis
  echo -e ""
  read -n 1 -s -r -p "Press any key to back"
  m-ssh
  exit 1
fi