#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : t.me/newbie_store24
# //====================================================

nama=$(cat /etc/xray/username)
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

function send_log() {
    CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
    KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
    TIME="10"
    URL="https://api.telegram.org/bot$KEY/sendMessage"
    TEXT="
<code>────────────────────</code>
<b>⚠️ NOTIFICATIONS MULTI LOGIN SSH⚠️</b>
<code>────────────────────</code>
<code>Username          : </code><code>$user</code>
<code>Limit IP          : </code><code>${limitip}</code>
<code>User Login        : </code><code>${lognow}</code>
<code>Akun Locked       : </code><code>Permanent</code>
<code>────────────────────</code>
"
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
## mengambil login ssh

systemctl reload ssh
if [ -e "/var/log/auth.log" ]; then
        LOG="/var/log/auth.log";
fi
if [ -e "/var/log/secure" ]; then
        LOG="/var/log/secure.log";
fi
for file in /tmp/login.db /tmp/login-db.db /tmp/login-db-pid.db; do
    [[ -e "$file" ]] && rm "$file"
done
data=( `ps aux | grep -i dropbear | awk '{print $2}'`);

cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.db;
for PID in "${data[@]}"
do
            cat /tmp/login-db.db | grep "dropbear\[$PID\]" > /tmp/login-db-pid.db;
            NUM=`cat /tmp/login-db-pid.db | wc -l`;
            USER=`cat /tmp/login-db-pid.db | awk -F"for " '{print $2}' | awk '{print $1}'`;
            IP=`cat /tmp/login-db-pid.db | awk -F"for " '{print $2}' | awk '{print $3}'`;
            if [ $NUM -eq 1 ]; then
                    echo -e "$PID - $USER - $IP" >> /tmp/login.db;
                    fi
done

cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/login-db.db
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
            cat /tmp/login-db.db | grep "sshd\[$PID\]" > /tmp/login-db-pid.db;
            NUM=`cat /tmp/login-db-pid.db | wc -l`;
            USER=`cat /tmp/login-db-pid.db | awk -F"for " '{print $2}' | awk '{print $1}'`;
            IP=`cat /tmp/login-db-pid.db | awk -F"for " '{print $2}' | awk '{print $3}'`;
            if [ $NUM -eq 1 ]; then
                    echo -e "$PID - $USER - $IP" >> /tmp/login.db;
        fi
done
clear
mulog="/tmp/login.db"
date=$(date)
data=( `ls /etc/kyt/limit/ssh/ip`)
banner "USER SSH MULTILOGIN"
garis_atas
printf "${YELLOW}   %-17s %-17s %2s${RESET}\n" "USERNAME" "LIMIT IP" "IP LOGIN"
garis_bawah
garis_atas
declare -a exceeded_users
for user in "${data[@]}"; do
    limitip=$(cat /etc/kyt/limit/ssh/ip/$user)
		cekcek=$(cat $mulog | grep "'""$user""'" | wc -l)
		
    if [[ $cekcek -gt $limitip ]]; then
        printf " %-17s %-18s %2s \n" "  $user" "$limitip" "$cekcek"
        exceeded_users+=("$user")
    fi

done
garis_bawah

if [[ ${#exceeded_users[@]} -eq 0 ]]; then
banner "SCRIPT BY $nama"
    read -n 1 -s -r -p "Tekan tombol apa saja untuk kembali"
    m-ssh
    exit 0
fi

read -p "Ingin mengunci akun yang melebihi batas? (Y/N): " confirm
if [[ "$confirm" =~ ^[Yy]$ ]]; then
			tput cuu 1 && tput el 

    lock_user() {
        user="$1"
        passwd -l "$user" > /dev/null
        pids=$(grep "'""$user""'" $mulog | awk '{print $1}')
        lognow=$(grep "'""$user""'" $mulog | awk '{print $1}' | wc -l)
        for pid in $pids; do
            kill -9 $pid
            echo -e "$pid - $user" >> /root/log-lock.txt
        done
		send_log        
        #echo "passwd -u $user" | at now + 60 minutes > /dev/null 2>&1
    }

    for user in "${exceeded_users[@]}"; do
        lock_user "$user"
    done

    center "$(echo -e "${YELLOW}Akun yang melebihi batas telah dikunci.${RESET}")"
	garis
banner "SCRIPT BY $nama"
    read -n 1 -s -r -p "Tekan tombol apa saja untuk kembali"
fi
m-ssh