#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

MYIP=$(curl -sS ipv4.icanhazip.com)
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${RESET}"
    echo -e "   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    echo -e "     ${YELLOW}Buy access permissions for scripts${RESET}"
    echo -e "             ${YELLOW}Contact Admin :${RESET}"
    echo -e "      ${CYAN}Telegram${RESET} t.me/newbie_store24"
    echo -e "      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
	read -p "Tekan Enter untuk kembali ke menu..."
    exit
  fi
}
checking_sc
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
clear
LIMITSSH_SCRIPT="/usr/bin/limitsship"
CRON_FILE="/etc/cron.d/limitsship"

check_cron_status() {
    if [ -e "$CRON_FILE" ]; then
        echo -e "${WHITE}${BOLD} Status Limit IP : ${RESET}${YELLOW}[ON]${RESET}"
    else
        echo -e "${WHITE}${BOLD} Status Limit IP : ${RESET}${RED}[OFF]${RESET}"
    fi
}

start_cron() {
clear

banner "AUTO LOCK LIMIT IP SSH"
echo
    read -p "Input Menit Untuk LimitIP (15-59): " menit
    if [[ ! "$menit" =~ ^[1-9]$|^[1-5][0-9]$ ]]; then
        echo -e "${RED}Input tidak valid.${RESET}"
        return
    fi

    # Membuat isi tugas cron
    CRON_ENTRY="*/$menit * * * * root $LIMITSSH_SCRIPT"

    # Menambahkan atau memperbarui tugas cron
    echo -e "SHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\n$CRON_ENTRY" | tee "$CRON_FILE" > /dev/null

    # Pastikan izin file dan tugas cron
    chmod +x "$LIMITSSH_SCRIPT"
    chmod 644 "$CRON_FILE"
    
clear
banner "AUTO LOCK LIMIT IP SSH"
garis
center "$(echo -e "${YELLOW}LIMIT IP BERHASIL DINYALAKAN${RESET}")"
garis
echo
check_cron_status
echo -e " ${WHITE}${BOLD}Auto Shutdown   :${RESET} ${YELLOW}$menit Menit${RESET}"
echo
garis
banner "SCRIPT BY $nama"
}

stop_cron() {
    rm -f "$CRON_FILE"
	clear
banner "AUTO LOCK LIMIT IP SSH"
    garis
    center "$(echo -e "${YELLOW}LIMIT IP BERHASIL DIMATIKAN${RESET}")"
	garis
    echo
    echo -e "${WHITE}${BOLD} Status  :${RESET} ${RED}NonActive${RESET}"
    echo
    garis
banner "SCRIPT BY $nama"
}

function Environment(){
clear
banner "AUTO LOCK LIMIT IP SSH"
garis
center "$(check_cron_status)"
garis
echo -e "${WHITE}${BOLD}"
echo -e " 1.  Start Limit Ip ssh "
echo -e " 2.  Stopp Limit Ip ssh "
echo -e " x.  Back to Menu "
echo -e "${RESET}"
garis
echo
}
Environment
while true; do
echo ""
read -p "Select From Options [1/2 or x] :  " REPLY
    case $REPLY in
        1) clear ; start_cron ; break;;
        2) clear ; stop_cron ; break;;
        0|x) clear ; m-ssh ; break;;
        *) 	
			tput cuu 1 && tput el 
			tput cuu 1 && tput el 
            echo -e "\nInput tidak valid! Silakan coba lagi."
            sleep 2
			tput cuu 1 && tput el  
            ;;
    esac
	tput cuu 1 && tput el  
    read -p "Tekan Enter untuk kembali ke menu..."
    tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done
