#!/bin/bash

source /usr/bin/ui.sh

DF='${RESET}'
Bold='${BOLD}'
Blink='${BLINK}'
yell='${YELLOW}'
PURPLE='${MAGENTA}'
cyan='${CYAN}'
LRED='${RED}'
Lgreen='${GREEN}'
Lyellow='${YELLOW}'
clear

echo -e "${GREEN}loading...${RESET}"
clear

limitip=$(systemctl status vmip | grep running | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
limitquota=$(systemctl status limitvmess | grep running | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
# STATUS SERVICE
if [[ $limitip == "running" ]]; then 
   status_limip="${GREEN}ON$RESET${blue} │$RESET"
else
   status_limip="${RED}OFF${RESET} "
fi

# Status 
if [[ $limitquota == "running" ]]; then 
   status_limq="${GREEN}ON$RESET${blue} │$RESET"
else
   status_limq="${RED}OFF${RESET} "
fi

echo -e "${CYAN}┌──────────────────────────────────────────┐${RESET}"
echo -e "       Status limit ip      : $status_limip"
echo -e "       Status limit quota   : $status_limq"
echo -e "${CYAN}└──────────────────────────────────────────┘${RESET}"
echo -e "${CYAN}┌──────────────────────────────────────────┐${RESET}"
echo -e " ${WHITE}1. TURN OFF LIMIT IP VIA LOCK${RESET}"
echo -e " ${WHITE}2. TURN ON  LIMIT IP VIA LOCK${RESET}"
echo -e " ${WHITE}3. TURN OFF LIMIT QUOTA VIA LOCK${RESET}"
echo -e " ${WHITE}4. TURN ON  LIMIT QUOTA VIA LOCK${RESET}"
echo -e " ${WHITE}x. Back To Main Menu ${RESET}"
echo -e "${CYAN}└──────────────────────────────────────────┘${RESET}"

# Fungsi untuk
start_limip() {
clear
    systemctl enable vmip
	systemctl enable vlip
	systemctl enable trip
	systemctl start vmip
	systemctl start vlip
	systemctl start trip
clear
    echo -e "Limit IP Xray ${GREEN}Diaktifkan${RESET}."
	sleep 2
	limit-on-off
}

stop_limip() {
clear
    systemctl disable vmip
	systemctl disable vlip
	systemctl disable trip
	systemctl stop vmip
	systemctl stop vlip
	systemctl stop trip
clear
    echo -e "Limit IP Xray ${RED}Dinonaktifkan${RESET}."
	sleep 2
	limit-on-off
}

start_limq() {
clear
    systemctl enable limitvmess
	systemctl enable limitvless
	systemctl enable limittrojan
	systemctl start limitvless
	systemctl start limitvless
	systemctl start limittrojan
clear
    echo -e "Limit IP Xray ${GREEN}Diaktifkan${RESET}."
	sleep 2
	limit-on-off
}

stop_limq() {
clear
    systemctl disable limitvmess
	systemctl disable limitvless
	systemctl disable limittrojan
	systemctl stop limitvmess
	systemctl stop limitvless
	systemctl stop limittrojan
clear
    echo -e "Limit IP Xray ${RED}Dinonaktifkan${RESET}."
	sleep 2
	limit-on-off
}

# Pilihan fungsi
read -p "Select From Options [ 0 - 5 ] : " menu
case $menu in
    1) stop_limip ;;
    2) start_limip ;;
    3) stop_limq ;;
    4) start_limq ;;
    *)
        clear ;
        menu
        ;;
esac