#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://nevpn.site${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://whatsapp.nevpn.site${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
banner "LOCK MEMBER SSH"
printf "  ${YELLOW}%-18s %-16s  %2s${RESET}\n" "USERNAME" "EXP DATE" "STATUS"
garis
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "P" ]]; then
printf "  %-17s %-17s %2s\n" "$AKUN" "$exp" "UNLOCKED"
fi
fi
done < /etc/passwd
garis
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
garis
center "$(print_rainbow "Masukan Usernamenya")"
garis  
read -p "Input Username you want to lock: " User

if [[ -z "$User" || ! $(getent passwd "$User") ]]; then
    clear
garis
    center "$(print_rainbow "[ LOCK ACCOUNT SSH ]")"
garis  
    echo -e ""
    center "$(printf "${RED}AKUN TIDAK DITEMUKAN !!!${RESET}")"
    echo -e ""
garis
    echo -e ""
    read -n 1 -s -r -p "Press any key to back"
    m-ssh
	exit 1
fi
passwd -l "$User"
clear
garis
    center "$(print_rainbow "[ LOCK ACCOUNT SSH ]")"
garis  
echo -e "$WHITE$BOLD"
echo -e " Username  : $User"
echo -e " Status    :${RESET} ${RED}LOCKED!!${RESET} "
echo -e ""
garis
banner "SCRIPT BY $nama"