#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
g="${GREEN}"
cyan='\e[36m'
r='\e[91m'
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}
function Newbie_Banner_Log() {
BOX_WIDTH=48
TEXT="[ LOG TIME BACKUP ] "
TEXT_LENGTH=${#TEXT}
LEFT_PADDING=$(( (BOX_WIDTH - TEXT_LENGTH) / 2 ))
RIGHT_PADDING=$(( BOX_WIDTH - TEXT_LENGTH - LEFT_PADDING ))
LEFT_SPACE=$(printf '%*s' $LEFT_PADDING '')
RIGHT_SPACE=$(printf '%*s' $RIGHT_PADDING '')
print_rainbow " ════════════════════════════════════════════════"
print_rainbow " ${LEFT_SPACE}${TEXT}${RIGHT_SPACE}"
print_rainbow " ════════════════════════════════════════════════"
}
KIRI="${GREEN}>\033[1;33m>${RED}>${RED}$RESET"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
function Backup_Vps() {
  backup
}
function Restore_Vps() {
  restore
}
function Restore() {
  restorepot
}
function Auto_Backup_Vps() {
  autobackup
}
function Menu_Features() {
banner "MENU MANAGER AUTOBACKUP"
 garis_atas
  echo -e "${WHITE}${BOLD}  1. Backup Vps Data  ${RESET}"
  echo -e "${WHITE}${BOLD}  2. Restore Vps Data ${RESET}"
  echo -e "${WHITE}${BOLD}  3. Restore Vps Dari Sc Potato ${RESET}"
  echo -e "${WHITE}${BOLD}  4. Auto Backup Vps ${RESET}"
  echo -e "${RED}  x. Exit ${RESET}"
 garis_bawah
}
Menu_Features
while true; do
echo ""
read -p "Select [1/4 or x] :  " Opt
case $Opt in
1) clear ; Backup_Vps ; break ;;
2) clear ; Restore_Vps ; break ;;
3) clear ; Restore ; break ;;
4) clear ; Auto_Backup_Vps ; break ;;
x|X) clear ; menu ; break ;;
        *) 	
			tput cuu 1 && tput el 
			tput cuu 1 && tput el 
            echo -e "\nInput tidak valid! Silakan coba lagi."
            sleep 2
			tput cuu 1 && tput el  
            ;;
    esac
	tput cuu 1 && tput el  
    read -p "Tekan Enter untuk kembali ke menu..."
    tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done
