#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
g="${GREEN}"
cyan='\e[36m'
r='\e[91m'
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}
function Newbie_Banner_Log() {
BOX_WIDTH=48
TEXT="[ CHANGE YOUR RESPON HEADER ] "
TEXT_LENGTH=${#TEXT}
LEFT_PADDING=$(( (BOX_WIDTH - TEXT_LENGTH) / 2 ))
RIGHT_PADDING=$(( BOX_WIDTH - TEXT_LENGTH - LEFT_PADDING ))
LEFT_SPACE=$(printf '%*s' $LEFT_PADDING '')
RIGHT_SPACE=$(printf '%*s' $RIGHT_PADDING '')
print_rainbow " ════════════════════════════════════════════════"
print_rainbow " ${LEFT_SPACE}${TEXT}${RIGHT_SPACE}"
print_rainbow " ════════════════════════════════════════════════"
}
KIRI="${GREEN}>\033[1;33m>${RED}>${RED}$RESET"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc

function Create_Bot_Notif() {
  create-bot-notif
}
function Info_Port() {
  prot
}
function change_respon() {
    local file_path="/etc/handeling"
    Newbie_Banner_Log
    echo -e "$WHITE$BOLD"
    echo -e "Tindakan ini akan membuat semua user SSH disconnect!!" 
	read -p "Apakah Anda ingin melanjutkan? (y/n): " confirm
    if [[ ! $confirm =~ ^[Yy]$ ]]; then
        echo "Operasi dibatalkan."
        return
    fi
	clear
	Newbie_Banner_Log
    read -p "Masukkan respon yang diinginkan : " user_response
    read -p "Masukkan warna respon (contoh: green, red, blue): " user_color
    echo -e "$user_response\n$user_color" | sudo tee "$file_path" > /dev/null
    echo -e "$RESET"
    systemctl restart ws 
banner "SCRIPT BY $nama"
}

function Menu_Lambofgod() {
    garis
    center "$(printf " ${YELLOW}[ SERVICE MANAGEMENT ]${RESET}")"
    garis
    printf "  ${WHITE}${BOLD}(1) Running Service    (5) SpeedTest${RESET}\n"
    printf "  ${WHITE}${BOLD}(2) Restart Service    (6) Delete All Account Exp${RESET}\n"
    printf "  ${WHITE}${BOLD}(3) Monitoring BW ${RESET}\n"
    printf "  ${WHITE}${BOLD}(4) Monitoring System${RESET}\n"
    garis
    center "$(printf " ${YELLOW}[ ADMINISTRATION ]${RESET}")"
    garis
    printf "  ${WHITE}${BOLD}(7) Factory Reset      (9) Pointing Domain${RESET}\n"
    printf "  ${WHITE}${BOLD}(8) Rebuild VPS        (10) Auto-Reboot${RESET}\n"
    garis
    center "$(printf " ${YELLOW}[ FIX & CONFIGURATION ]${RESET}")"
    garis
    printf "  ${WHITE}${BOLD}(11) Change Banner     (14) Fix HAProxy${RESET}\n"
    printf "  ${WHITE}${BOLD}(12) Change Domain     (15) Fix Domain${RESET}\n"
    printf "  ${WHITE}${BOLD}(13) Change Respon     (16) Install Bot WhatsApp${RESET}\n"
    garis
    center "$(printf " ${YELLOW}[ CLEANUP OPTIONS ]${RESET}")"
    garis
    printf "  ${WHITE}${BOLD}(17) Clear Cache      (19) Clear Cache File${RESET}\n"
    printf "  ${WHITE}${BOLD}(18) Clear Logs${RESET}\n"
    garis
    center "$(printf " ${YELLOW}[ SYSTEM INFORMATION ]${RESET}")"
    garis
    printf "  ${WHITE}${BOLD}(20) Info Service Port  (22) Limit-on-off XRAY${RESET}\n"
    printf "  ${WHITE}${BOLD}(21) Information System${RESET}\n"
    garis
    center "$(printf " ${WHITE}${BOLD}(23) Back to Main Menu${RESET}     ${RED}(x) Exit${RESET}")"
    garis
}

function Select_Menu() {
while true; do
echo ""
read -p "Select From Options [1-22 or x] :  " NB
case $NB in
1) clear ; run ; break ;;
2) clear ; reset ; break ;;
3) clear ; bw ; break ;;
4) clear ; gotop ; break ;;
5) clear ; speedtest ; break ;;
6) clear ; xp ; break ;;
7) clear ; Factreset ; break ;;
8) clear ; rebuild; break ;;
9) clear ; cf ; break ;;
10) clear ; autoreboot ; break ;;
11) clear ; nano /etc/issue.net ; break ;;
12) clear ; change-domain ; break ;;
13) clear ; change_respon ; break ;;
14) clear ; fixhap ; break ;;
15) clear ; fixcert ; break ;;
16) clear ; wget -qO /root/setup.sh "https://drive.google.com/u/4/uc?id=1n7e_9KsBfLpGDxpAoWQWJ-2Cub9rcZWT&export=download" && chmod +x setup.sh && ./setup.sh 1dJ9-d9o720HvasS7KudfB51gSe0gaYY9; break ;;
17) clear ; clearcache ; break ;;
18) clear ; clearlog ; break ;;
19) clear ; delet-cache-file ; break ;;
20) clear ; Info_Port ; break ;;
21) clear ; about ; break ;;
22) clear ; limit-on-off ; break ;;
23) clear ; menu ; break ;;
        0|x|X) 
            clear
            figlet "NEWBIE STORE" | lolcat
            exit 0
            ;;
        *) 	
			tput cuu 1 && tput el 
			tput cuu 1 && tput el 
            echo -e "\nInput tidak valid! Silakan coba lagi."
            sleep 2
			tput cuu 1 && tput el  
            ;;
    esac
	tput cuu 1 && tput el  
    read -p "Tekan Enter untuk kembali ke menu..."
    tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done
}
banner "MENU MANAGER SYSTEM"
Menu_Lambofgod
Select_Menu
