#!/bin/bash

clear;clear
clear

source /usr/bin/ui.sh

# . Create Ssh
function Create_Ssh() {
  add-ssh
}

# . Create Triall
function Create_Trial() {
  trial-ssh
}

# . Hapus akun ssh
function Delete_Ssh(){
  del-ssh
}

# . List Member ssh
function List_Member() {
  member-ssh
}

# . Auto Kill ssh
function Auto_Kill() {
  auto-kill
}

# . Check user Login
function Check_Mullog() {
  limitssh-ip
}

# . Delete Expiry
function Delete_Exp() {
  delexp
}

# . Limit On off
function Limit_On_Off() {
  limitssh-on-off
}

#. Renew Ssh
function Renew_Ssh() {
  renew-ssh
}

# . Lock Ssh
function Lock() {
  lock
}

# . Unlock Ssh
function Unlock() {
  unlock
}

# . Detail Akun Ssh
function Details_Account(){
  user-ssh
}

function Monitor_Ssh() {
  ceklim
}

function Recovery_Ssh() {
  recover
}

# . Banner Ssh

function Menu_Features() {
garis
center "$(printf " ${YELLOW}[ ACCOUNT MANAGEMENT ]${RESET}")"
garis
printf "  ${WHITE}${BOLD}(1) Check Users       (5) Trial Account${RESET}\n"
printf "  ${WHITE}${BOLD}(2) Create Account    (6) List Accounts${RESET}\n"
printf "  ${WHITE}${BOLD}(3) Delete Account    (7) Expired Accounts${RESET}\n"
printf "  ${WHITE}${BOLD}(4) Renew Account${RESET}\n"
garis
center "$(printf " ${YELLOW}[ SECURITY & SETTINGS ]${RESET}")"
garis
printf "  ${WHITE}${BOLD}(8) Lock Account     (11) Toggle Limit IP${RESET}\n"
printf "  ${WHITE}${BOLD}(9) Unlock Account   (12) Auto Kill Account${RESET}\n"
printf " ${WHITE}${BOLD}(10) Edit Limit IP${RESET}\n"
garis
center "$(printf " ${YELLOW}[ OTHER OPTIONS ]${RESET}")"
garis
printf " ${WHITE}${BOLD}(13) Account Details  (14) Check Login UDP${RESET}\n"
garis
center "$(printf " ${WHITE}${BOLD}(15) Back to Main Menu${RESET}     ${RED}(x) Exit${RESET}")"
garis
}

banner "SSH-DROPBEAR-OPENVPN"
Menu_Features
while true; do
echo ""
    read -p "Select From Options [1-15 or x] :  " Ltt
    case $Ltt in
        1) clear ; Monitor_Ssh ; break;;
        2) clear ; Create_Ssh ; break;;
        3) clear ; Delete_Ssh ; break;;
        4) clear ; renew-ssh ; break;;
        5) clear ; Create_Trial ; break;;
        6) clear ; List_Member ; break;;
        7) clear ; Delete_Exp ; break;;
        8) clear ; Lock ; break;;
        9) clear ; Unlock ; break;;
        10) clear ; ganti-ip-ssh ; break;;
        11) clear ; Limit_On_Off ; break;;
        12) clear ; Check_Mullog ; break;;
        13) clear ; Details_Account ; break;;
        14) clear ; cekudp ; break;;
        15) clear ; menu ; break;;
        0|x) 
            clear
            figlet "NEWBIE STORE" | lolcat
            exit 0
            ;;
        *) 	
			tput cuu 1 && tput el 
			tput cuu 1 && tput el 
            echo -e "\nInput tidak valid! Silakan coba lagi."
            sleep 2
			tput cuu 1 && tput el  
            ;;
    esac
	tput cuu 1 && tput el  
    read -p "Tekan Enter untuk kembali ke menu..."
    tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done