#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
 TAG="V2.4.3"
ASSET="xray"
OWNER="kertasbaru"
REPO="vip"
nama=$(cat /etc/xray/username)

ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
function Cek_User_Login() {
  # Menampilkan output dari cek-vme
  cek-vme
}

# Fungsi list member
function List_Member() {
  # Menampilkan output dari member-xray
  member-vme
}

# Fungsi untuk membuat akun
function Create_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ CREATE ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Create Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Create Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Create Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Create_Vmess ;;   # Create Vmess Account
    2) clear ; Create_Vless ;;   # Create Vless Account
    3) clear ; Create_Trojan ;;  # Create Trojan Account
    x) clear ; Main_Menu ;;           # Kembali ke menu utama
    *) echo "Invalid Option!" ; Create_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk create Vmess Account
function Create_Vmess() {
  clear
add-vme
}

# Menu untuk create Vless Account
function Create_Vless() {
  clear
add-vle
}

# Menu untuk create Trojan Account
function Create_Trojan() {
  clear
add-tro
}
function Trial_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ TRIAL ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Trial Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Trial Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Trial Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Trial_Vmess ;;   # Create Vmess Account
    2) clear ; Trial_Vless ;;   # Create Vless Account
    3) clear ; Trial_Trojan ;;  # Create Trojan Account
    x) clear ; Main_Menu ;;           # Kembali ke menu utama
    *) echo "Invalid Option!" ; Trial_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk create Vmess Account
function Trial_Vmess() {
  clear
trial-vme
}

# Menu untuk create Vless Account
function Trial_Vless() {
  clear
trial-vle
}

# Menu untuk create Trojan Account
function Trial_Trojan() {
  clear
trial-tro
}
function Delete_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ DELETE ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Delete Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Delete Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Delete Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Delete_Vmess ;;   # Create Vmess Account
    2) clear ; Delete_Vless ;;   # Create Vless Account
    3) clear ; Delete_Trojan ;;  # Create Trojan Account
    x) clear ; Main_Menu ;;           # Kembali ke menu utama
    *) echo "Invalid Option!" ; Delete_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk create Vmess Account
function Delete_Vmess() {
  clear
del-vme
}

# Menu untuk create Vless Account
function Delete_Vless() {
  clear
del-vle
}

# Menu untuk create Trojan Account
function Delete_Trojan() {
  clear
del-tro
}

function Renew_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ RENEW ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Renew Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Renew Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Renew Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Renew_Vmess ;;   # Create Vmess Account
    2) clear ; Renew_Vless ;;   # Create Vless Account
    3) clear ; Renew_Trojan ;;  # Create Trojan Account
    x) clear ; Main_Menu ;;           # Kembali ke menu utama
    *) echo "Invalid Option!" ; Renew_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk create Vmess Account
function Renew_Vmess() {
  clear
renew-vme
}

# Menu untuk create Vless Account
function Renew_Vless() {
  clear
renew-vle
}

# Menu untuk create Trojan Account
function Renew_Trojan() {
  clear
renew-tro
}

# Menu untuk Check Config Account
function Check_Config_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ CHECK CONFIG ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Check Config Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Check Config Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Check Config Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; check-vme ;;   # Check Vmess Account Config
    2) clear ; check-vle ;;   # Check Vless Account Config
    3) clear ; check-tro ;;  # Check Trojan Account Config
    x) clear ; Main_Menu ;;           # Kembali ke menu utama
    *) echo "Invalid Option!" ; Check_Config_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk Recovery Account
function Recovery_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ RECOVERY ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Recover Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Recover Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Recover Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; recover-vm ;;   # Recover Vmess Account
    2) clear ; recover-vl ;;   # Recover Vless Account
    3) clear ; recover-tr ;;  # Recover Trojan Account
    x) clear ; Main_Menu ;;           # Kembali ke menu utama
    *) echo "Invalid Option!" ; Recovery_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk Edit Limit IP Account
function Edit_Limit_IP() {
  clear
  garis
  center "$(printf "${YELLOW}[ EDIT LIMIT IP ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Edit Limit IP Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Edit Limit IP Vless\n"
  printf "${WHITE}${BOLD}  3.)  Edit Limit IP Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Edit_Limit_Vmess_IP ;;   # Edit Vmess IP Limit
    2) clear ; Edit_Limit_Vless_IP ;;   # Edit Vless IP Limit
    3) clear ; Edit_Limit_Trojan_IP ;;  # Edit Trojan IP Limit
    x) clear ; Main_Menu ;;              # Kembali ke menu utama
    *) echo "Invalid Option!" ; Edit_Limit_IP ;; # Jika input tidak valid
  esac
}

# Menu untuk Edit Limit Bandwidth Account
function Edit_Limit_Bandwidth() {
  clear
  garis
  center "$(printf "${YELLOW}[ EDIT LIMIT BW ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Edit Bandwidth Limit Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Edit Bandwidth Limit Vless\n"
  printf "${WHITE}${BOLD}  3.)  Edit Bandwidth Limit Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Edit_Vmess_Bandwidth ;;   # Edit Vmess Bandwidth Limit
    2) clear ; Edit_Vless_Bandwidth ;;   # Edit Vless Bandwidth Limit
    3) clear ; Edit_Trojan_Bandwidth ;;  # Edit Trojan Bandwidth Limit
    x) clear ; Main_Menu ;;               # Kembali ke menu utama
    *) echo "Invalid Option!" ; Edit_Limit_Bandwidth ;; # Jika input tidak valid
  esac
}

# Menu untuk Lock Account
function Lock_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ LOCK ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Lock Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Lock Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Lock Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Lock_Vmess ;;   # Lock Vmess Account
    2) clear ; Lock_Vless ;;   # Lock Vless Account
    3) clear ; Lock_Trojan ;;  # Lock Trojan Account
    x) clear ; Main_Menu ;;    # Kembali ke menu utama
    *) echo "Invalid Option!" ; Lock_Account ;; # Jika input tidak valid
  esac
}

# Menu untuk Unlock Account
function Unlock_Account() {
  clear
  garis
  center "$(printf "${YELLOW}[ UNLOCK ACCOUNT ]${RESET}\n")"
  garis
  garis
  printf "${WHITE}${BOLD}  1.)  Unlock Account Vmess\n"
  printf "${WHITE}${BOLD}  2.)  Unlock Account Vless\n"
  printf "${WHITE}${BOLD}  3.)  Unlock Account Trojan\n"
  printf "${WHITE}${BOLD}  x.)  Back to Main Menu\n"
  garis
  read -p "Select Account Type [1-3 or x] : " pilih_akun
  case $pilih_akun in
    1) clear ; Unlock_Vmess ;;   # Unlock Vmess Account
    2) clear ; Unlock_Vless ;;   # Unlock Vless Account
    3) clear ; Unlock_Trojan ;;  # Unlock Trojan Account
    x) clear ; Main_Menu ;;      # Kembali ke menu utama
    *) echo "Invalid Option!" ; Unlock_Account ;; # Jika input tidak valid
  esac
}
function Lock_Vmess() {
  clear
  lock-vm
}

function Unlock_Vmess() {
  clear
  unlock-vm
}

function Lock_Vless() {
  clear
  lock-vl
}

function Unlock_Vless() {
  clear
  unlock-vl
}

function Lock_Trojan() {
  clear
  lock-tr
}

function Unlock_Trojan() {
  clear
  unlock-tr
}

function Edit_Limit_Vmess_IP() {
  clear
  ganti-ip-vmess
}

function Edit_Limit_Vless_IP() {
  clear
  ganti-ip-vless
}

function Edit_Limit_Trojan_IP() {
  clear
  ganti-ip-trojan
}

function Edit_Vmess_Bandwidth() {
  clear
  change-vmess-qouta
}

function Edit_Vless_Bandwidth() {
  clear
  change-vless-qouta
}

function Edit_Trojan_Bandwidth() {
  clear
  change-trojan-qouta
}
function change_onering() {
  clear
banner "XRAY MANAGER"
  garis
  center "$(printf " ${YELLOW}[ SETUP ONE RING XRAY ]${RESET}")"
  garis
  systemctl stop xray
  wget -O /usr/local/bin/${ASSET} "https://github.com/${OWNER}/${REPO}/releases/download/${TAG}/${ASSET}"
  systemctl start xray
  garis
  center "$(printf " ${YELLOW}[ Succesfully Setup ]${RESET}")"
  garis
  printf "${WHITE}${BOLD}Link Apk V2rayang OneRing : https://github.com/${OWNER}/${REPO}/releases/download/${TAG}/v2rayNG_Onering_1.10.26_universal.apk${RESET}\n"
}

# Main Menu
function Main_Menu() { 
banner "XRAY MANAGER"
garis
center "$(printf " ${YELLOW}[ ACCOUNT MANAGEMENT ]${RESET}")"
garis
printf "  ${WHITE}${BOLD}(1) Check Users Login      (5) Delete Account${RESET}\n"
printf "  ${WHITE}${BOLD}(2) List Member            (6) Renew Accounts${RESET}\n"
printf "  ${WHITE}${BOLD}(3) Create Account         (7) Check Config Accounts${RESET}\n"
printf "  ${WHITE}${BOLD}(4) Trial Account${RESET}\n"
garis
center "$(printf " ${YELLOW}[ SECURITY & SETTINGS ]${RESET}")"
garis
printf "  ${WHITE}${BOLD}(8) Recovery Account      (11) Lock Account${RESET}\n"
printf "  ${WHITE}${BOLD}(9) Edit Limit IP Account (12) Unlock Account${RESET}\n"
printf " ${WHITE}${BOLD}(10) Edit Limit Bw Account (13) Setup Onering Metode${RESET}\n"
garis
center "$(printf " ${WHITE}${BOLD}(14) Back to Main Menu${RESET}     ${RED}(x) Exit${RESET}\n")"
garis
banner "SCRIPT BY $nama"
while true; do
echo ""
	  read -p "Select Option [1-13 or x] : " main_menu_option
	  case $main_menu_option in
		1) clear ; Cek_User_Login ; break ;;    # Cek User Login
		2) clear ; List_Member ; break ;;       # List Member
		3) clear ; Create_Account ; break ;;    # Langsung menuju menu pembuatan akun
		4) clear ; Trial_Account ; break ;;        # Pilih jenis akun
		5) clear ; Delete_Account ; break ;;   # Delete Account Trojan
		6) clear ; Renew_Account ; break ;;    # Renew Account Trojan
		7) clear ; Check_Config_Account ; break ;;    # Check Config Account Trojan
		8) clear ; Recovery_Account ; break ;;         # Recovery Account Trojan
		9) clear ; Edit_Limit_IP ; break ;;        # Edit Limit IP Account Trojan
		10) clear ; Edit_Limit_Bandwidth ; break ;; # Edit Limit Bandwidth Account Trojan
		11) clear ; Lock_Account ; break ;;     # Lock Account Trojan
		12) clear ; Unlock_Account ; break ;;   # Unlock Account Trojan
		13) clear ; change_onering ; break ;;   # Unlock Account Trojan
	    14) clear ; menu ; break ;;
        0|x|X) 
            clear
            figlet "WUZZSTORE" | lolcat
            exit 0
            ;;                     # Exit
        *) 	
			tput cuu 1 && tput el 
			tput cuu 1 && tput el 
            echo -e "\nInput tidak valid! Silakan coba lagi."
            sleep 2
			tput cuu 1 && tput el  
            ;;
    esac
	tput cuu 1 && tput el  
    read -p "Tekan Enter untuk kembali ke menu..."
    tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done

}

Main_Menu