#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

MYIP=$(curl -sS ipv4.icanhazip.com);
clear
banner "MEMBER SSH"
garis_atas
 printf "${YELLOW}   %-17s %-17s %2s${RESET}\n" "USERNAME" "EXP DATE" "STATUS"
garis_bawah
garis_atas
while read expired
do
AKUN="$(echo $expired | cut -d: -f1)"
ID="$(echo $expired | grep -v nobody | cut -d: -f3)"
exp="$(chage -l $AKUN | grep "Account expires" | awk -F": " '{print $2}')"
status="$(passwd -S $AKUN | awk '{print $2}' )"
if [[ $ID -ge 1000 ]]; then
if [[ "$status" = "L" ]]; then
 printf "   %-17s %-18s %2s \n" "$AKUN" "$exp" "LOCKED${NORMAL}"
else
 printf "   %-17s %-18s %2s \n" "$AKUN" "$exp" "UNLOCKED${NORMAL}"
fi
fi
done < /etc/passwd
JUMLAH="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
garis_bawah
garis_atas
center "$(echo -e "${YELLOW}Account number:${RESET}${WHITE}${BOLD} $JUMLAH${RESET} ${YELLOW}user${RESET}")"
garis_bawah
banner "SCRIPT BY $nama"