#!/bin/bash

source /usr/bin/ui.sh

ORANGE='${CYAN}'
PURPLE='${MAGENTA}'
CYAN='\033[0;36m'
LIGHT='\033[0;37m'

nama=$(cat /etc/xray/username)
# . Liner 
function baris_panjang() {
  echo -e "${CYAN} ——————————————————————————————————— ${RESET} "
}

duration=3
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}${RESET}"
sleep 0.5
    done
}

# Menjalankan animasi loading

# Menampilkan pesan setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "${GREEN}Succes${RESET}"
sleep 1
clear
}

banner ""
	baris_panjang
	echo -e "${CYAN}            LIST MEMBER ${RESET} "
	baris_panjang
    echo "" 
    baris_panjang 
    echo -e "${YELLOW} Username ${RESET}" 
	baris_panjang
#!# " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | column -t | sort | uniq
    echo ""
    baris_panjang
    echo ""
banner "SCRIPT BY $NAME"
	read -p "Enter Back To Menu "
	menu