#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================

nama=$(cat /etc/xray/username)
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

function Daftar_Member_Vmess() {
grep -E "^### " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}     %-23s %-12s${RESET}\n" "$user" "$date"
done
}

function Daftar_Member_Vless() {
grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}     %-23s %-12s${RESET}\n" "$user" "$date"
done
}

function Daftar_Member_Trojan() {
#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}     %-23s %-12s${RESET}\n" "$user" "$date"
done
}

banner "CHECK XRAY ACCOUNT"
garis
center "$(printf "${YELLOW}[ ACCOUNT VMESS ]${RESET}\n")"
garis
printf "${YELLOW}     %-23s %-12s${RESET}\n" "USERNAME" "EXP DATE"
garis_atas
Daftar_Member_Vmess
garis_bawah
echo "     "
garis
center "$(printf "${YELLOW}[ ACCOUNT VLESS ]${RESET}\n")"
garis
printf "${YELLOW}     %-23s %-12s${RESET}\n" "USERNAME" "EXP DATE"
garis_atas
Daftar_Member_Vless
garis_bawah
echo "     "
garis
center "$(printf "${YELLOW}[ ACCOUNT TROJAN ]${RESET}\n")"
garis
printf "${YELLOW}     %-23s %-12s${RESET}\n" "USERNAME" "EXP DATE"
garis_atas
Daftar_Member_Trojan
garis_bawah
banner "SCRIPT BY $nama"