#!/bin/bash
clear;clear

source /usr/bin/ui.sh

MYIP=$(cat /etc/xray/ipvps)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
LOCAL_IP_FILE="/etc/izin/ip"   # simpan data GitHub di sini
GITHUB_IP_URL="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
update_data() {
    echo "Mengupdate data dari GitHub..."
    mkdir -p $(dirname "$LOCAL_IP_FILE")
    curl -sS "$GITHUB_IP_URL" -o "$LOCAL_IP_FILE"
    echo "Data berhasil diupdate!"
}
if [[ "$1" == "update" ]]; then
    update_data
    exit 0
fi
if [[ ! -f "$LOCAL_IP_FILE" ]]; then
    echo "File lokal tidak ditemukan, mengambil data dari GitHub..."
    update_data
fi
MYIP=$(cat /usr/bin/.ipvps)
username=$(grep -wE "$MYIP" "$LOCAL_IP_FILE" | awk '{print $2}')
echo "$username" >/usr/bin/user
valid=$(grep -wE "$MYIP" "$LOCAL_IP_FILE" | awk '{print $3}')
echo "$valid" >/usr/bin/e

# Fungsi cek masa aktif
checking_sc() {
    useexp="$valid"
    if [[ "$useexp" == "Lifetime" ]]; then
        return
    fi

    date_list_epoch=$(date -d "$date_list" +%s)
    useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

    if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
        echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
        echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
        echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
        echo -e ""
        echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
        echo -e ""
        echo -e "  ${YELLOW}🔒 Your VPS${RESET} $MYIP ${YELLOW}Has been Banned${RESET}"
        echo -e ""
        echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
        echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
        echo -e ""
        echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
        echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
        echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
        echo -e ""
        echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
        exit 1
    fi
}
checking_sc

VERSIONOLD=$(cat /opt/.ver)
VERSIONNEW=$(curl -sS https://raw.githubusercontent.com/kertasbaru/os/main/versi)

if [[ "$VERSIONOLD" != "$VERSIONNEW" ]]; then
  wget -q https://raw.githubusercontent.com/kertasbaru/os/main/menu/update.sh && chmod +x update.sh && ./update.sh
fi

dorpaket() {
    cd ~ || exit 1

    if [ ! -d "me-cli" ]; then
        echo "[INFO] Fitur Dor belum ada, mulai download..."
        gdown --id 15ZfWf6ZQELqzbZba5vNgwkmps439LnDA -O me-cli.zip || {
            echo "[ERROR] Gagal download me-cli.zip"
            return 1
        }

        unzip -o me-cli.zip || {
            echo "[ERROR] Gagal extract me-cli.zip"
            rm -f me-cli.zip
            return 1
        }

        rm -f me-cli.zip
        cd me-cli || return 1
        chmod +x setup.sh
        ./setup.sh
    else
        echo "[INFO] Fitur Dor sudah ada, langsung jalankan..."
        cd me-cli || return 1
    fi

    python3 main.py
}

clear
######################################
# // DETAIL ORDER IZIN IP
username=$(cat /usr/bin/user)
exp=$(cat /usr/bin/e)
######################################
clear
# // DAYS LEFT
if [[ "$valid" == "Lifetime" ]]; then
  masaaktif="Lifetime"
else
  d1=$(date -d "$valid" +%s)
  d2=$(date -d "$today" +%s)
  certifacate=$(((d1 - d2) / 86400))
  if [[ $certifacate -le 0 ]]; then
    masaaktif="EXPIRED"
  else
    masaaktif="${certifacate} Day"
  fi
fi

clear
######################################
# // GETTINGS SYSTEM
OS=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1| sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
RAM=$(free -m | awk 'NR==2 {print $2}')
UPTIME=$(uptime -p | cut -d " " -f 2-10)
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
DOMAIN=$(cat /etc/xray/domain)
# MUTIARA=$(cat /etc/kata_mutiara)
MUTIARA=$(cat /opt/.ver)
NET_SPEED=$(cat /etc/traffic | awk '/Download/ {print $2}')
kemarin=$(date -d "-1 days" +"%m-%d")
hariini=$(date -d "0 days" +"%m-%d")
kemarin1=$(date -d "-1 days" +"%m/%d")
hariini1=$(date -d "0 days" +"%m/%d")
bulan=$(date +"%b '%y")
bulan1=$(date +"%Y-%m")
kemarin2=$(vnstat -d | grep -w "${kemarin}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
kemarin3=$(vnstat -d | grep -w "${kemarin1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $kemarin2 == "" ]]; then
bwkmrn=${kemarin3}
else
bwkmrn=${kemarin2}
fi
if [[ $bwkmrn == "" ]]; then
bwkmrn1="NEWVPS "
else
bwkmrn1=${bwkmrn}
fi
hariini2=$(vnstat -d | grep -w "${hariini}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
hariini3=$(vnstat -d | grep -w "${hariini1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $hariini2 == "" ]]; then
bwhari=${hariini3}
else
bwhari=${hariini2}
fi
rxtdy2=$(vnstat -d | grep -w "${hariini}" | awk '{print $2" "substr ($3 ,1 ,1) substr ($3 ,3 ,1)}') 
rxtdy3=$(vnstat -d | grep -w "${hariini1}" | awk '{print $2" "substr ($3 ,1 ,1) substr ($3 ,3 ,1)}') 
if [[ $rxtdy2 == "" ]]; then
rxtdy=${rxtdy3}
else
rxtdy=${rxtdy2}
fi
txtdy2=$(vnstat -d | grep -w "${hariini}" | awk '{print $5" "substr ($6 ,1 ,1) substr ($6 ,3 ,1)}') 
txtdy3=$(vnstat -d | grep -w "${hariini1}" | awk '{print $5" "substr ($6 ,1 ,1) substr ($6 ,3 ,1)}') 
if [[ $txtdy2 == "" ]]; then
txtdy=${txtdy3}
else
txtdy=${txtdy2}
fi
bulan2=$(vnstat -m | grep -w "${bulan}" | awk '{print $9" "substr ($10 ,1 ,1) substr ($10 ,3 ,1)}') 
bulan3=$(vnstat -m | grep -w "${bulan1}" | awk '{print $8" "substr ($9 ,1 ,1) substr ($9 ,3 ,1)}') 
if [[ $bulan2 == "" ]]; then
bwbln=${bulan3}
else
bwbln=${bulan2}
fi
vlx=$(grep -c -E "^#& " "/etc/xray/config.json")
let VLESS_COUNT=$vlx/2
# \\ Vmess account //
vmc=$(grep -c -E "^### " "/etc/xray/config.json")
let VMESS_COUNT=$vmc/2
# \\ Trojan account //
SSH_COUNT="$(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd | wc -l)"
trx=$(grep -c -E "^#! " "/etc/xray/config.json")
let TROJAN_COUNT=$trx/2
# \\ shadowsocks account //
ssx=$(grep -c -E "^#!# " "/etc/xray/config.json")
let ssa=$ssx/2
let xra=($VLESS_COUNT+$VMESS_COUNT+$TROJAN_COUNT+$ssa)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
ssh_service=$(systemctl status ws | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)

clear
######################################
# RUNNING HAPROXY
######################################
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="ON"
else
   status_haproxy="OFF"
fi
######################################
# RUNNING XRAY
######################################
if [[ $xray_service == "running" ]]; then 
   status_xray="ON"
else
   status_xray="OFF"
fi
######################################
# RUNNING NGINX
######################################
if [[ $nginx_service == "running" ]]; then 
   status_nginx="ON"
else
   status_nginx="OFF"
fi
if [[ $ssh_service == "running" ]]; then 
   status_ssh="ON"
else
   status_ssh="OFF"
fi
######################################
# RUNNING DROPBEAR
######################################
services=("haproxy" "nginx" "ws" "dropbear" "xray" "udp-custom" )

# Cek status masing-masing service
status_service="${YELLOW}GOOD${RESET}"
for service in "${services[@]}"; do
    if [[ "$(systemctl is-active $service)" != "active" ]]; then
        status_service="${RED}ERROR $service${RESET}"
        break
    fi
done
format_speed() {
    local speed=$1
    if (( $(echo "$speed >= 1000" | bc -l) )); then
        printf "%.2f Gbps\n" "$(echo "$speed / 1000" | bc -l)"
    else
        printf "%.2f Mbps\n" "$speed"
    fi
}

speed_value=$NET_SPEED
formatted_speed=$(format_speed "$speed_value")

# // NEWBIE TUNNELING | NB PROJECT
# // WHATSAPP : 082326322300
# // TELEGRAM : NEWBIE_STORE24

function Service_System_Operating() {

print_rainbow " ════════════════════════════════════════════════════════════"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${RED}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${GREEN}%-20s${RESET}\n" "CLIENTS" "$username" "OS" "$OS"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${GREEN}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${GREEN}%-20s${RESET}\n" "RAM" "$RAM MB" "UPTIME" "$UPTIME"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${GREEN}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${GREEN}%-20s${RESET}\n" "IP" "$MYIP" "ISP" "$ISP"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${RED}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${GREEN}%-20s${RESET}\n" "EXPIRED" "$masaaktif" "DOMAIN" "$DOMAIN"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${GREEN}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${GREEN}%-20s${RESET}\n" "RX" "$rxtdy" "LAST" "$bwkmrn1"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${GREEN}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${GREEN}%-20s${RESET}\n" "TX" "$txtdy" "TODAY" "$bwhari"
printf " ${WHITE}${BOLD}%-7s${RESET} : ${GREEN}%-20s${RESET} ${WHITE}${BOLD}%-6s${RESET} : ${BRED}%-8s${RESET}\n" "REGION" "$CITY" "MONTH" "$bwbln"
print_rainbow " ────────────────────────────────────────────────────────────"
}
function Service_Status() {
center "$(echo -e "[ SERVICE STATUS - $status_service ]")"
print_rainbow " ────────────────────────────────────────────────────────────"
center "$(echo -e "${WHITE}${BOLD}PROXY${RESET} ${GREEN}: $status_haproxy${RESET}")"
center "$(echo -e "${WHITE}${BOLD}NGINX${RESET} ${GREEN}: $status_nginx${RESET}")"
center "$(printf "${WHITE}${BOLD} %s${RESET} : ${GREEN}%s${RESET} ${WHITE}${BOLD} %s${RESET} : ${GREEN}%s${RESET}\n" "SSH" "$status_ssh" "XRAY" "$status_xray")"
center "$(printf "${WHITE}${BOLD} %s${RESET} : ${GREEN}%s${RESET} ${WHITE}${BOLD} %s${RESET} : ${GREEN}%s${RESET}\n" "SSH ACCOUNT" "$SSH_COUNT" "XRAY ACCOUNT" "$xra")"
print_rainbow " ════════════════════════════════════════════════════════════"
}
function List_All_Account() {
print_rainbow " ╭───────────────────────────────────────────────────────────╮"
center "$(echo -e "$MUTIARA")" | lolcat
print_rainbow " ╰───────────────────────────────────────────────────────────╯"
}
function Acces_Use_Command() {
#center "$(printf "$YELLOW[ MENU ]${RESET}\n")"
#print_rainbow " ════════════════════════════════════════════════════════════"
echo -e "  ${WHITE}${BOLD} (1) SSH/OPENVPN                    (6) ADMIN MENU  ${RESET}"
echo -e "  ${WHITE}${BOLD} (2) XRAY MANAGER                   (7) BOT TELEGRAM  ${RESET}"
echo -e "  ${WHITE}${BOLD} (3) ADD BUG CONFIG                 (8) UPDATE SCRIPT  ${RESET}"
echo -e "  ${WHITE}${BOLD} (4) CHANGE WARNA                   (9) BACKUP & RESTORE  ${RESET}"
echo -e "  ${WHITE}${BOLD} (5) REGISTER IP                   (10) FEATURES  ${RESET}"
print_rainbow " ════════════════════════════════════════════════════════════"
printf "${RED}     %-43s${RESET}${WHITE}${BOLD}%-20s${RESET}\n" "[ REBOOT SYSTEM ]" "[ EXIT ]"
print_rainbow " ════════════════════════════════════════════════════════════"
}

checking_sc
banner "$(cat /etc/xray/username)"
Service_System_Operating
Service_Status
Acces_Use_Command
List_All_Account
while true; do
    echo ""
    read -p "Select From option [1/10 or x] :  " hallo
    case $hallo in
        1) clear ; m-ssh ; break ;;  # menu ssh
        2) clear ; m-xray ; break ;;  # menu vmess
        3) clear ; nano /etc/xray/.bug_optr ; break ;;  # menu vless
        4) clear ; change_warna ; break ;;  # menu trojan
        5) clear ; regisip ; break ;;  # menu shadowsocks
        6) clear ; main_menu ; break ;;  # menu noobzvps
        7) clear ; m-bot ; break ;;  # menu bot telegram
        8) clear ; wget -q https://raw.githubusercontent.com/kertasbaru/os/main/menu/update.sh && chmod +x update.sh && ./update.sh ; break ;;  # Update script
        9) clear ; m-bkp ; break ;;  # menu backup
        10) clear ; m-ftr ; break ;;  # menu managers
        11) clear ; reboot ;;  # reboot tetap berjalan
		tembak) clear ; dorpaket ; break ;;
        r) clear ; figlet BYE BYE | lolcat ; reboot ;;
        0|x) clear ; figlet WUZZSTORE | lolcat ; exit 0 ;;
        *)  
            tput cuu 1 && tput el   
            echo -e "${RED}Input tidak valid!${RESET} Silakan pilih menu yang benar." 
            sleep 2
            tput cuu 1 && tput el  
        ;;
    esac	   
		tput cuu 1 && tput el
	    read -p "Tekan Enter untuk kembali ke menu..."
		tput cuu 1 && tput el  
done
