#!/bin/bash
clear

source /usr/bin/ui.sh

echo -e "${GREEN}┌─────────────────────────────────────────────┐"
echo -e "${GREEN}│       >>> Service & Port                    │"
echo -e "${GREEN}│   - Open SSH                : 443, 80, 22   │"
echo -e "${GREEN}│   - Dropbear                : 443, 109, 143 │"
echo -e "${GREEN}│   - SSH Websocket SSL       : 443           │"
echo -e "${GREEN}│   - SSH Websocket           : 80, 8080, 2086│"
echo -e "${GREEN}│   - OpenVPN Websocket SSL   : 443           │"
echo -e "${GREEN}│   - OpenVPN TCP             : 443, 1194     │"
echo -e "${GREEN}│   - OpenVPN UDP             : 2200          │"
echo -e "${GREEN}│   - OpenVPN Websocket SSL   : 443           │"
echo -e "${GREEN}│   - XRAY Vmess TLS          : 443           │"
echo -e "${GREEN}│   - XRAY Vmess gRPC         : 443           │"
echo -e "${GREEN}│   - XRAY Vmess None TLS     : 80            │"
echo -e "${GREEN}│   - XRAY Vless TLS          : 443           │"
echo -e "${GREEN}│   - XRAY Vless gRPC         : 443           │"
echo -e "${GREEN}│   - XRAY Vless None TLS     : 80            │"
echo -e "${GREEN}│   - Trojan gRPC             : 443           │"
echo -e "${GREEN}│   - Trojan WS               : 443           │"
echo -e "${GREEN}│   - Shadowsocks WS          : 443           │"
echo -e "${GREEN}└─────────────────────────────────────────────┘"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
menu
