#!/bin/bash

source /usr/bin/ui.sh

PURPLE='${MAGENTA}'
CYAN='${CYAN}'
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${RESET}"
    echo -e "   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    echo -e "     ${YELLOW}Buy access permissions for scripts${RESET}"
    echo -e "             ${YELLOW}Contact Admin :${RESET}"
    echo -e "      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
	echo -e "      ${GREEN}Telegram${RESET} t.me/Newbie_Store24"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    sleep 10
	reboot
  fi
}
checking_sc
clear
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear
# Getting
function baris_panjang() {
  echo -e "${CYAN} ◇━━━━━━━━━━━━━━━━━◇ ${RESET}"
}

duration=6
frames=("██10%" "█████35%" "█████████65%" "█████████████80%" "█████████████████████90%" "█████████████████████████100%")

# Menghitung jumlah frame
num_frames=${#frames[@]}

# Menghitung jumlah iterasi
num_iterations=$((duration))

# Fungsi untuk menampilkan animasi loading berwarna

Loading_Animasi() {
    for ((i = 0; i < num_iterations; i++)); do
        clear
        index=$((i % num_frames))
        color_code=$((31 + i % 7))
echo ""
echo ""
echo ""
echo -e "\e[1;${color_code}m ${frames[$index]}${RESET}"
sleep 0.5
    done
}

# Menampilkan pesan Sukses setelah animasi selesai
function Loading_Succes() {
clear
echo -e  "${GREEN}Succes${RESET}"
sleep 0.1
clear
}

function Daftar_Account() {
grep -E "^#ssh# " "/etc/xray/.userall.db" | cut -d ' ' -f 2-3 | column -t | sort | uniq
}
MYIP=$(curl -sS ipv4.icanhazip.com);
clear
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "             List Member SSH Expaired                  "
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"      
echo "USERNAME          PASSWORD          "
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
Daftar_Account
echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "           Masukan Usernamenya              "
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}" 
echo "" 
	read -p " Username : " user
	if [ -z $user ]; then
    exit
    else
baris_panjang
    read -p " Expired (day)    : " masaaktif
baris_panjang
    read -p " Limit User (GB)  : " Quota
baris_panjang
    read -p " Limit User (IP)  : " iplimit
baris_panjang
echo ""
fi
Loading_Animasi
Loading_Succes
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$user
else
echo > /dev/null
fi
clear
Pass=$(grep -E "^#ssh#" "/etc/xray/.userall.db" |  grep -wE "${user}" | cut -d " " -f 3)
if [ -z $Pass ]; then
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "        Recovery Account Failed!             "
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"  
echo -e ""
echo -e "   Username Tidak Ditemukan      "
echo -e ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e ""
read -n 1 -s -r -p "Press any key to back"
exit 1
else
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $user
expi="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $user &> /dev/null
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
fi
if [ ! -e /etc/ssh ]; then
  mkdir -p /etc/ssh
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^#ssh#" | grep -wE "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
echo "#ssh# ${user} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
sed -i "/^#ssh# $user $Pass/d" /etc/xray/.userall.db
else
echo "#ssh# ${user} ${Pass} ${Quota} ${iplimit} ${expe}" >>/etc/ssh/.ssh.db
sed -i "/^#ssh# $user $Pass/d" /etc/xray/.userall.db
fi
clear
     
TEXT="
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH OVPN Account     </code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Username         : </code> <code>$user</code>
<code>Password         : </code> <code>$Pass</code>
<code>Limit Quota       ; </code> <code>$Quota</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>IP               : $IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH WEBSOCKET    : </code><code>$domain:80@$user:$Pass</code>
<code>SSH SSL          : </code><code>$domain:443@$user:$Pass</code>
<code>SSH UDP          : </code><code>$domain:1-65535@$user:$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Payload WSS      : </code><code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
OVPN Download : https://$domain:81/
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Save Link Account: </code>https://$domain:81/ssh-$user.txt
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Aktif Selama         : $masaaktif Hari
Dibuat Pada          : $tnggl
Berakhir Pada        : $expe
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

TEXT="<code>◇━━━━━━━━━━━━━━━━━◇
*_PEMBELIAN BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUK : SSH
-» REGION : $CITY
-» REQ CONFIG : 
-» REQ NAMA : $user
-» DEVICE : $iplimit IP
-» HARGA : 
-» AKTIF : $masaaktif HARI
-» TGL EXP : $expe
◇━━━━━━━━━━━━━━━━━◇
$nama </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf]"

# Details ACcount
function Details_Ssh(){
banner ""
echo -e "  ${WHITE}${BOLD}${REVERSE}SSH OPENVPN${RESET}"
baris_panjang
echo -e "${WHITE} Remark      : $user ${RESET}"
echo -e "${WHITE} Password    : $Pass ${RESET}"
echo -e "${WHITE} Limit Ip    : ${iplimit} Devic ${RESET}"
echo -e "${WHITE} Domain      : $domain ${RESET}"
echo -e "${WHITE} ISP         : $ISP ${RESET} "
echo -e "${WHITE} OpenSSH     : 443, 80, 22 ${RESET}"
echo -e "${WHITE} Port UDP    : 1-65535 ${RESET}"
echo -e "${WHITE} SSH WS      : 80,8080,8880,2082 ${RESET}"
echo -e "${WHITE} SSL/TLS     : 443 ${RESET}"
echo -e "${WHITE} OVPN UDP    : 2200 ${RESET}"
baris_panjang
}

function Copy_Faste(){
echo -e "${WHITE} Port 80     : $domain:80@$user:$Pass ${RESET}"
echo -e "${WHITE} Port 443    : $domain:443@$user:$Pass ${RESET}"
echo -e "${WHITE} Udp Custom  : $domain:1-65535@$user:$Pass${RESET}"
echo -e "${WHITE} OpenVpn     : https://$domain:81/ "
echo -e "${WHITE} Account     : https://$domain:81/ssh-$user.txt "
}

function Details_Payload(){
baris_panjang
echo -e "${WHITE} Payload WS  : ${PAYLOADWS}${RESET}"
baris_panjang
echo -e "${WHITE} Payload TLS : ${PAYLOADTLS}${RESET}"
baris_panjang
echo -e "${WHITE} Payload ENCD: ${PAYLOADHANCED}${RESET}"
baris_panjang
}

function Expiry_Details(){
echo -e "${YELLOW} Days in    : $masaaktif Day ${RESET}"
echo -e "${YELLOW} Expiry in  : $expe ${RESET}"
}

banner ""
Details_Ssh
Copy_Faste
Details_Payload
Expiry_Details
banner "SCRIPT BY $nama"