#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)

garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
function Daftar_Account() {
grep -E "^#& " "/etc/xray/.userall.db" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}  %-9s %-12s${RESET}\n" "$user" "$date"
done
}
banner "CHECK VMESS ACCOUNT"
printf "${WHITE}${BOLD}   %-25s %-12s${RESET}\n" "USERNAME" "UUID"
garis_atas
Daftar_Account
garis_bawah
  echo -e "${WHITE}${BOLD}"
  read -rp " Username         : " -e user
  	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi
  if grep -i -w -q "$user" /etc/xray/config.json; then
    clear
banner "CHECK VMESS ACCOUNT"
    garis
    echo ""
    echo -e "${RED} Name Salah: Username sudah terdaftar, silakan gunakan nama lain.${RESET}"
    echo ""
    garis
banner "SCRIPT BY $nama"
  fi
    read -p " Expired (day)    : " masaaktif
    read -p " Limit User (GB)  : " Quota
    read -p " Limit User (IP)  : " iplimit
  echo -e "${RESET}"
clear
uuid=$(grep -E "^#&" "/etc/xray/.userall.db" |  grep -wE "${user}" | cut -d " " -f 3 | sort | uniq | tail -n1)
if [ -z $uuid ]; then
garis
center "$(printf "${RED}[ Recovery Account Failed! ]${RESET}\n")"
garis  
echo -e ""
echo -e "   UUID Tidak Valid"
echo -e ""
garis
read -n 1 -s -r -p "Press any key to back"
m-xray
exit 1
else
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"

if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
  echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
  sed -i "/^#& $user/d" /etc/xray/.userall.db
else
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db
sed -i "/^#& $user/d" /etc/xray/.userall.db
fi
clear
cat >/var/www/html/vless-$user.txt <<-END

======================
$nama 
======================
# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

======================
Link Akun Vless 
======================
Link TLS      : 
${vlesslink1}
======================
Link none TLS : 
${vlesslink2}
======================
Link GRPC     : 
${vlesslink3}
======================
Days in  : $masaaktif Day
Expired  : $expe

END

clear
curl -s -o /dev/null -X POST "https://api.telegram.org/bot$KEY/sendMessage" \
-F chat_id="$CHATID" \
-F parse_mode="HTML" \
-F text="◇━━━━━━━━━━━━━━━━━◇
      XRAY/VLESS
◇━━━━━━━━━━━━━━━━━◇
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : <code>${uuid}</code>
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vless-grpc
◇━━━━━━━━━━━━━━━━━◇
LINK TLS  
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink1}</code>
◇━━━━━━━━━━━━━━━━━◇
LINK NTLS 
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink2}</code>
◇━━━━━━━━━━━━━━━━━◇
LINK GPRC 
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink3}</code>
◇━━━━━━━━━━━━━━━━━◇
Format OpenClash : https://${domain}:81/vless-$user.txt
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
◇━━━━━━━━━━━━━━━━━◇
"
     
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇
*_PEMBELIAN BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUK : VLESS
-» REGION : $CITY
-» REQ CONFIG : 
-» REQ NAMA : $user
-» DEVICE : $iplimit IP
-» HARGA : 
-» AKTIF : $masaaktif HARI
-» TGL EXP : $expe
◇━━━━━━━━━━━━━━━━━◇
$nama </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
fi

clear
function Details_Account() {
printf "${WHITE}${BOLD} Remarks     : ${user} ${RESET}\n"
printf "${WHITE}${BOLD} Domain      : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota  : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} User Ip     : ${iplimit} IP${RESET}\n"
printf "${WHITE}${BOLD} port TLS    : 443-900${RESET}\n"
printf "${WHITE}${BOLD} port WS     : 80,8880,8080${RESET}\n"
printf "${WHITE}${BOLD} User ID     : ${uuid}${RESET}\n"
printf "${WHITE}${BOLD} Locations.  : $CITY${RESET}\n"
printf "${WHITE}${BOLD} ISP         : $ISP${RESET}\n"
printf "${WHITE}${BOLD} Encryption  : none${RESET}\n"
printf "${WHITE}${BOLD} Path TLS    : /vless ${RESET}\n"
printf "${WHITE}${BOLD} ServiceName : vless-grpc${RESET}\n"
}

function Link_Json() {
garis
printf "${WHITE}${BOLD} Link TLS    : ${vlesslink1}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link NTLS   : ${vlesslink2}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link GRPC   : ${vlesslink3}${RESET}\n"
garis
printf "${WHITE}${BOLD} OpenClash   : https://${domain}:81/vless-$user.txt${RESET}\n"
}

function Details_Expiry() {
garis
printf "${RED} Days in     : $masaaktif Day ${RESET}\n"
printf "${RED} Expiry      : $expe ${RESET}\n"
}
banner "CHECK VMESS ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"