#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)

garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
IP=$(curl -sS ipv4.icanhazip.com)
clear
function Daftar_Account() {
grep -E "^#! " "/etc/xray/.userall.db" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}  %-9s %-12s${RESET}\n" "$user" "$date"
done
}
banner "RECOVERY TROJAN ACCOUNT"
printf "${WHITE}${BOLD}   %-25s %-12s${RESET}\n" "USERNAME" "UUID"
garis_atas
Daftar_Account
garis_bawah
  echo -e "${WHITE}${BOLD}"
  read -rp " Username         : " -e user
  	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi
  if grep -i -w -q "$user" /etc/xray/config.json; then
    clear
banner "RECOVERY TROJAN ACCOUNT"
    garis
    echo ""
    echo -e "${RED} Name Salah: Username sudah terdaftar, silakan gunakan nama lain.${RESET}"
    echo ""
    garis
banner "SCRIPT BY $nama"
  fi
    read -p " Expired (day)    : " masaaktif
    read -p " Limit User (GB)  : " Quota
    read -p " Limit User (IP)  : " iplimit
  echo -e "${RESET}"
clear
uuid=$(grep -E "^#!" "/etc/xray/.userall.db" |  grep -wE "${user}" | cut -d " " -f 3 | sort | uniq | tail -n1)
if [ -z $uuid ]; then
garis
center "$(printf "${RED}[ Recovery Account Failed! ]${RESET}\n")"
garis  
echo -e ""
echo -e "   UUID Tidak Valid"
echo -e ""
garis
read -n 1 -s -r -p "Press any key to back"
m-xray
exit 1
else
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# Link Trojan Akun
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

cat >/var/www/html/trojan-$user.txt <<-END
======================

# Format Trojan GO/WS

- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

# Format Trojan gRPC

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc
	
FORMAT LINK
======================
Link Akun Trojan 
======================
Link TLS          : 
${trojanlink}
======================
Link NTLS          : 
${trojanlink2}
======================
Link GRPC        : 
${trojanlink1}
======================
Days in  : $masaaktif Day
Expired  : $expe
END
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
  echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
  sed -i "/^#! $user/d" /etc/xray/.userall.db
else
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db
sed -i "/^#! $user/d" /etc/xray/.userall.db
fi
clear
curl -s -o /dev/null -X POST "https://api.telegram.org/bot$KEY/sendMessage" \
-F chat_id="$CHATID" \
-F parse_mode="HTML" \
-F text="◇━━━━━━━━━━━━━━━━━◇
      XRAY/TROJAN
◇━━━━━━━━━━━━━━━━━◇
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : <code>${uuid}</code>
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : trojan-grpc
◇━━━━━━━━━━━━━━━━━◇
TROJAN TLS
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink}</code>
◇━━━━━━━━━━━━━━━━━◇
TROJAN NTLS
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink2}</code>
◇━━━━━━━━━━━━━━━━━◇
TROJAN gRPC
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink1}</code>
◇━━━━━━━━━━━━━━━━━◇
Format OpenClash : https://${domain}:81/trojan-$user.txt
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
◇━━━━━━━━━━━━━━━━━◇
"

TEXT="<code>◇━━━━━━━━━━━━━━━━━◇
*_PEMBELIAN BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUK : TROJAN
-» REGION : $CITY
-» REQ CONFIG : 
-» REQ NAMA : $user
-» DEVICE : $iplimit IP
-» HARGA : 
-» AKTIF : $masaaktif HARI
-» TGL EXP : $expe
◇━━━━━━━━━━━━━━━━━◇
$nama </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
fi
clear
function Details_Account() {
printf "${WHITE}${BOLD} Remarks      : ${user}${RESET}\n"
printf "${WHITE}${BOLD} Host/IP      : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota   : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} User Ip      : ${iplimit} IP${RESET}\n"
printf "${WHITE}${BOLD} Port NTLS    : 443-900${RESET}\n"
printf "${WHITE}${BOLD} port WS      : 80,8880,8080${RESET}\n"
printf "${WHITE}${BOLD} Key          : ${uuid}${RESET}\n"
printf "${WHITE}${BOLD} ISP          : $ISP${RESET}\n"
printf "${WHITE}${BOLD} Path         : /trojan-ws${RESET}\n"
printf "${WHITE}${BOLD} ServiceName  : trojan-grpc${RESET}\n"
}

function Link_Json() {
garis
printf "${WHITE}${BOLD} Link TLS     : ${trojanlink}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link NTLS    : ${trojanlink2}${RESET}\n"
garis 
printf "${WHITE}${BOLD} Link GRPC    : ${trojanlink1}${RESET}\n"
garis
printf "${WHITE}${BOLD} OpenClash    : https://${domain}:81/trojan-$user.txt${RESET}\n"
}

function Details_Expiry() {
garis
echo -e " ${YELLOW} Days in     : $masaaktif Day ${RESET} "
echo -e " ${YELLOW} Expiry in   : $expe ${RESET} "
}

banner "RECOVERY TROJAN ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"