#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)

garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
function Daftar_Account() {
grep -E "^### " "/etc/xray/.userall.db" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}  %-9s %-12s${RESET}\n" "$user" "$date"
done
}
banner "CHECK VMESS ACCOUNT"
printf "${WHITE}${BOLD}   %-25s %-12s${RESET}\n" "USERNAME" "UUID"
garis_atas
Daftar_Account
garis_bawah
  echo -e "${WHITE}${BOLD}"
  read -rp " Username         : " -e user
  	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi
  if grep -i -w -q "$user" /etc/xray/config.json; then
    clear
banner "CHECK VMESS ACCOUNT"
    garis
    echo ""
    echo -e "${RED} Name Salah: Username sudah terdaftar, silakan gunakan nama lain.${RESET}"
    echo ""
    garis
banner "SCRIPT BY $nama"
  fi
    read -p " Expired (day)    : " masaaktif
    read -p " Limit User (GB)  : " Quota
    read -p " Limit User (IP)  : " iplimit
  echo -e "${RESET}"
clear
uuid=$(grep -E "^###" "/etc/xray/.userall.db" |  grep -wE "${user}" | cut -d " " -f 3 | sort | uniq | tail -n1)
if [ -z $uuid ]; then
garis
center "$(printf "${RED}[ Recovery Account Failed! ]${RESET}\n")"
garis  
echo -e ""
echo -e "   UUID Tidak Valid"
echo -e ""
garis
read -n 1 -s -r -p "Press any key to back"
m-xray
exit 1
else
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json

asu=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"

cat >/var/www/html/vmess-$user.txt <<-END

======================
$nama
======================
# Format Vmess WS TLS

- name: Vmess-$user-WS TLS
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess WS Non TLS

- name: Vmess-$user-WS Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess gRPC

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

======================
 Link Akun Vmess
======================
Link TLS         : 
${vmesslink1}
======================
Link none TLS    : 
${vmesslink2}
======================
Link GRPC        : 
${vmesslink3}
======================
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
======================

END
if [ ! -e /etc/vmess ]; then
  mkdir -p /etc/vmess
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vmess/ip
echo -e "$iplimit" > /etc/kyt/limit/vmess/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vmess/${user}
fi
DATADB=$(cat /etc/vmess/.vmess.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vmess/.vmess.db
  echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vmess/.vmess.db
  sed -i "/^### $user/d" /etc/xray/.userall.db
else
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vmess/.vmess.db
sed -i "/^### $user/d" /etc/xray/.userall.db
fi
clear

TEXT="<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>      XRAY/VMESS</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : <code>${uuid}</code>
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vmess-grpc
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code> VMESS WS TLS</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>${vmesslink1}</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>VMESS WS NO TLS</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>${vmesslink2}</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code> VMESS gRPC</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>${vmesslink3}</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Format OpenClash : https://${domain}:81/vmess-$user.txt
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
     
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇
*_PEMBELIAN BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUK : VMESS
-» REGION : $CITY
-» REQ CONFIG : 
-» REQ NAMA : $user
-» DEVICE : $iplimit IP
-» HARGA : 
-» AKTIF : $masaaktif HARI
-» TGL EXP : $expe
◇━━━━━━━━━━━━━━━━━◇
$nama </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
fi
clear
function Details_Account() {
printf "${WHITE}${BOLD} Remarks       : ${user}${RESET}\n"
printf "${WHITE}${BOLD} Domain        : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota    : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} User Ip       : ${iplimit} IP${RESET}\n"
printf "${WHITE}${BOLD} Port TLS      : 400,8443${RESET}\n"
printf "${WHITE}${BOLD} port WS       : 80,8880,8080,2082${RESET}\n"
printf "${WHITE}${BOLD} Key           : ${uuid}${RESET}\n"
printf "${WHITE}${BOLD} Localtions    : $CITY${RESET}\n"
printf "${WHITE}${BOLD} ISP           : $ISP${RESET}\n"
printf "${WHITE}${BOLD} AlterId       : 0${RESET}\n"
printf "${WHITE}${BOLD} Security      : auto${RESET}\n"
printf "${WHITE}${BOLD} Network       : ws${RESET}\n"
printf "${WHITE}${BOLD} Path          : /vmess${RESET}\n"
printf "${WHITE}${BOLD} Dynamic Path  : yourbug/vmess${RESET}\n"
printf "${WHITE}${BOLD} ServiceName   : vmess-grpc${RESET}\n"
}

function Link_Json() {
garis
printf "${WHITE}${BOLD} Link TLS      : ${vmesslink1}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link WS       : ${vmesslink2}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link GRPC     : ${vmesslink3}${RESET}\n"
garis
printf "${WHITE}${BOLD} OpenClash     : https://${domain}:81/vmess-$user.txt${RESET}\n"
}

function Details_Expiry() {
garis
printf "${RED} Days in       : $masaaktif Day ${RESET}\n"
printf "${RED} Expiry        : $expe ${RESET}\n"
}

banner "CHECK VMESS ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"