#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}
function Loading() {
BOX_WIDTH=48
TEXT="[ PROCESSING, PLEASE WAIT.. ] "
TEXT_LENGTH=${#TEXT}
LEFT_PADDING=$(( (BOX_WIDTH - TEXT_LENGTH) / 2 ))
RIGHT_PADDING=$(( BOX_WIDTH - TEXT_LENGTH - LEFT_PADDING ))
LEFT_SPACE=$(printf '%*s' $LEFT_PADDING '')
RIGHT_SPACE=$(printf '%*s' $RIGHT_PADDING '')
print_rainbow " ════════════════════════════════════════════════"
print_rainbow " ${LEFT_SPACE}${TEXT}${RIGHT_SPACE}"
print_rainbow " ════════════════════════════════════════════════"
}

# // Get Bot
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# Valid Script
MYIP=$(curl -sS ipv4.icanhazip.com)
PROFIL=$(curl -sS https://raw.githubusercontent.com/kertasbaru/izin/main/ip | grep -wE $MYIP | awk '{print $2}')
data_ip=$(curl -sS https://raw.githubusercontent.com/kertasbaru/izin/main/ip | grep -wE $MYIP | awk '{print $6}')
checking_sc() {
if [[ -n "$data_ip" || "$data_ip" -gt 0 ]]; then
    echo -ne
  else
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
eval $(wget -qO- "https://drive.google.com/u/4/uc?id=1eutPTYsea7xYx1mNBWDQ_g1Yx3ZPNimF")
function register() {
AVAILABLE=$(curl -sS https://raw.githubusercontent.com/kertasbaru/izin/main/ip | grep -wE $MYIP | awk '{print $6}')
echo -e "${YELLOW}      $AVAILABLE ${RESET} ${WHITE}${BOLD} IP DAPAT ANDA REGISTER${RESET}"
}

add-ip() {
    today=`date -d "0 days" +"%Y-%m-%d"`
    git clone "${REPO}"  &> /dev/null
clear
banner "REGISTER IP"
garis
center "$(printf "${WHITE}${BOLD} MASUKAN IP VPS YANG BELUM DI DAFTAR !${RESET}\n")"
garis
	while true; do
	echo -e "$WHITE$BOLD"
    read -p " Input IP Address                   : " ipqu
    echo -e "${RESET}"
	if [[ -z "$ipqu" || "$ipqu" == "exit" ]]; then
    echo -e "${RED} IP kosong atau exit! Proses Kembali Ke Menu sebelumnya.${RESET}"
	sleep 1
    regisip
    exit 1
    elif ! [[ "$ipqu" =~ ^[0-9.]+$ ]]; then
    echo -e "${RED} Input IP Salah! Silakan Periksa IP anda lagi.${RESET}" 
	sleep 2
	tput cuu 4 && tput ed 
    else
      break
    fi
  done

    CLIENT_EXISTS=$(grep -w $ipqu /root/izin/ip | wc -l)
    
    if [[ ${CLIENT_EXISTS} == '1' ]]; then
        echo -r "${RED}IP Already Exist !${RESET}"
		resgisip
        exit 1
    fi
	
	while true; do
	echo -e "$WHITE$BOLD"
    read -p " Input Username (EX : NEWBIE_STORE) : " name
	echo -e "${RESET}"
	if [[ -z "$name" ]]; then
    echo -e "${RED} Nama Tidak Boleh Kosong! Silahkan Coba Lagi.${RESET}"
	sleep 2
	tput cuu 4 && tput ed 
	elif [[ ! "$name" =~ ^[a-zA-Z][a-zA-Z0-9_-]*$ ]]; then
    echo -e "${RED} Nama tidak valid! Nama harus diawali huruf.${RESET}"
	sleep 2
	tput cuu 4 && tput ed 
    else
      break
    fi
	done
	while true; do
	echo -e "$WHITE$BOLD"
    read -p " Input waktu expired                :" exp
	echo -e "$RESET"
	if [[ -z "$exp" || "$exp" == 0 ]]; then
    echo -e "${RED} Waktu Exp Tidak Boleh Kosong atau 0! Silahkan Coba Lagi.${RESET}"
	sleep 2
	tput cuu 4 && tput ed 
	elif [[ ! "$exp" =~ ^[0-9]+$ ]]; then
    echo -e "${RED} Waktu Exp Harus Berupa Angka! Silakan Coba lagi.${RESET}"
	sleep 2
	tput cuu 4 && tput ed 
    else
      break
    fi
	done
clear
Loading
    exp2=`date -d "${exp} days" +"%Y-%m-%d"`
    if grep -q "^# $PROFIL" "/root/izin/ip"; then
        sed -i "/^# $PROFIL/a ### ${name} ${exp2} ${ipqu}" "/root/izin/ip"
    else
        echo -e "# $PROFIL\n### ${name} ${exp2} ${ipqu}" >> "/root/izin/ip"
    fi
    exp1=$(grep "$MYIP" /root/izin/ip | cut -d " " -f3)
    JUMLAH=$(grep "$MYIP" /root/izin/ip | cut -d " " -f6)
    SISA=$((JUMLAH - 1))
    sed -i "s/### $PROFIL $exp1 $MYIP ON $JUMLAH VIP/### $PROFIL $exp1 $MYIP ON $SISA VIP/" /root/izin/ip
    cd /root/izin
    git config --global user.email "${EMAILGIT}" &> /dev/null
    git config --global user.name "${USERGIT}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m izin &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/${USERGIT}/izin.git &> /dev/null
    git push -f https://${GH}@github.com/${USERGIT}/izin.git &> /dev/null
    cd 
 rm -rf /root/izin
    TEXT="
    ───────────────────────────
       SUCCESS REGISTERED IP VPS
    ───────────────────────────
    USERNAME       : $name
    IP Address     : <code>$ipqu</code>
    Registered On  : $today
    Expired On     : $exp2
    ───────────────────────────
    "
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
    garis
    center "$(printf "${YELLOW}SUCCESS ADD IP VPS${RESET}\n")"
	garis
    garis_atas
    echo -e "${WHITE}${BOLD}   USERNAME   :${RESET}${YELLOW} $name ${RESET}"
    echo -e "${WHITE}${BOLD}   IP ADDRESS :${RESET}${YELLOW} $ipqu ${RESET}"
    echo -e "${WHITE}${BOLD}   REGISTERED :${RESET}${YELLOW} $today ${RESET}"
    echo -e "${WHITE}${BOLD}   EXPIRED ON :${RESET}${YELLOW} $exp2 ${RESET}"
    garis_bawah
banner "SCRIPT BY $nama"
}

del-ip() {
    git clone "${REPO}"  &> /dev/null
    clear
banner "REGISTER IP"
	center "$(printf "${WHITE}${BOLD} LIST IP VPS !${RESET}\n")"
    garis_atas
	grep -E "^###" "/root/izin/ip" | cut -d ' ' -f 2-4 | sort -k2,2 -t' ' | uniq | awk -v WHITEBLD="$WHITE$BOLD" -v NC="$RESET" '{printf "%s  %-15s | %-11s | %-10s%s\n", WHITEBLD, $1, $2, $3, NC}'
    garis_bawah
	while true; do
	echo -e "$WHITE$BOLD"
    read -p " Input IP Address : " ipdel
    echo -e "${RESET}"
	if [[ -z "$ipdel" || "$ipdel" == "exit" ]]; then
    echo -e "${RED} IP kosong atau exit! Proses Kembali Ke Menu sebelumnya.${RESET}"
	sleep 1
    regisip
    exit 1
    elif ! [[ "$ipdel" =~ ^[0-9.]+$ ]]; then
    echo -e "${RED} Input IP Salah! Silakan Periksa IP anda lagi.${RESET}" 
	sleep 2
	tput cuu 4 && tput ed 
    else
      break
    fi
  done
    clear
	Loading
    name=$(cat /root/izin/ip | grep $ipdel | cut -d " " -f2)
    exp=$(cat /root/izin/ip | grep $ipdel | cut -d " " -f3)
    sed -i "/^### $name $exp $ipdel/d" /root/izin/ip
cd /root/izin
    git config --global user.email "${EMAILGIT}" &> /dev/null
    git config --global user.name "${USERGIT}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m izin &> /dev/null
    git branch -M main &> /dev/null
	git remote add origin https://github.com/${USERGIT}/izin.git &> /dev/null
	git push -f https://${GH}@github.com/${USERGIT}/izin.git &> /dev/null
    cd 
 rm -rf /root/izin
TEXT1="
───────────────────────────
    SUCCESS DELETE IP VPS
───────────────────────────
USERNAME       : $name
IP Address     : <code>$ipdel</code>
Expired On     : $exp
───────────────────────────
"
     
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT1&parse_mode=html" $URL >/dev/null
clear
garis
center "$(printf "${YELLOW}DONE DELETE IP VPS${RESET}\n")"
garis
garis
echo -e "${WHITE}${BOLD} USERNAME   :${RESET}${YELLOW} $name${RESET}"
echo -e "${WHITE}${BOLD} IP ADDRESS :${RESET}${YELLOW} $ipdel${RESET}"
echo -e "${WHITE}${BOLD} EXPIRED ON :${RESET}${YELLOW} $exp${RESET}"
garis
banner "SCRIPT BY $nama"
}

renew-ip() {
git clone "${REPO}"  &> /dev/null
clear
banner "REGISTER IP"
center "$(printf "${YELLOW}RENEW IP VPS${RESET}\n")"
garis_atas
	grep -E "^###" "/root/izin/ip" | cut -d ' ' -f 2-4 | sort -k2,2 -t' ' | uniq | awk -v WHITEBLD="$WHITE$BOLD" -v NC="$RESET" '{printf "%s  %-15s | %-11s | %-10s%s\n", WHITEBLD, $1, $2, $3, NC}'
garis_bawah
	while true; do
	echo -e "$WHITE$BOLD"
    read -p " Input IP Address To Renew : " ipdel
    echo -e "${RESET}"
	if [[ -z "$ipdel" || "$ipdel" == "exit" ]]; then
    echo -e "${RED} IP kosong atau exit! Proses Kembali Ke Menu sebelumnya.${RESET}"
	sleep 1
    regisip
    exit 1
    elif ! [[ "$ipdel" =~ ^[0-9.]+$ ]]; then
    echo -e "${RED} Input IP Salah! Silakan Periksa IP anda lagi.${RESET}" 
	sleep 2
	tput cuu 4 && tput ed 
    else
      break
    fi
  done
  	while true; do
	echo -e "$WHITE$BOLD"
    read -p " Input Days                : " days
	echo -e "$RESET"
	if [[ -z "$days" || "$days" == 0 ]]; then
    echo -e "${RED} Waktu Days Tidak Boleh Kosong atau 0! Silahkan Coba Lagi.${RESET}"
	sleep 2
	tput cuu 4 && tput ed 
	elif [[ ! "$days" =~ ^[0-9]+$ ]]; then
    echo -e "${RED} Waktu Days Harus Berupa Angka! Silakan Coba lagi.${RESET}"
	sleep 2
	tput cuu 4 && tput ed 
    else
      break
    fi
	done
clear
Loading
name=$(cat /root/izin/ip | grep $ipdel | cut -d " " -f2)
exp=$(cat /root/izin/ip | grep $ipdel | cut -d " " -f3)
now=$(date +%Y-%m-%d)
d1=$(date -d "$exp" +%s)
d2=$(date -d "$now" +%s)
exp2=$(( (d1 - d2) / 86400 ))
exp3=$(($exp2 + $days))
exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
sed -i "s/### $name $exp $ipdel/### $name $exp4 $ipdel/" /root/izin/ip
exp1=$(grep "$MYIP" /root/izin/ip | cut -d " " -f3)
JUMLAH=$(grep "$MYIP" /root/izin/ip | cut -d " " -f6)
SISA=$((JUMLAH - 1))
sed -i "s/### $PROFIL $exp1 $MYIP ON $JUMLAH VIP/### $PROFIL $exp1 $MYIP ON $SISA VIP/" /root/izin/ip
cd /root/izin
git config --global user.email "${EMAILGIT}" &> /dev/null
git config --global user.name "${USERGIT}" &> /dev/null
rm -rf .git &> /dev/null
git init &> /dev/null
git add . &> /dev/null
git commit -m izin &> /dev/null
git branch -M main &> /dev/null
git remote add origin https://github.com/${USERGIT}/izin.git &> /dev/null
git push -f https://${GH}@github.com/${USERGIT}/izin.git &> /dev/null
cd 
 rm -rf /root/izin
clear
     
TEXT2="
───────────────────────────
    SUCCESS RENEW  IP VPS
───────────────────────────
USERNAME       : $name
IP Address     : <code>$ipdel</code>
Expired On     : $exp4
───────────────────────────
"
     
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT2&parse_mode=html" $URL >/dev/null
clear
echo ""
garis
center "$(printf "${YELLOW}DONE RENEW IP VPS${RESET}\n")"
garis
echo -e "${WHITE}${BOLD}  USERNAME   :${RESET}${YELLOW} $name"
echo -e "${WHITE}${BOLD}  IP ADDRESS :${RESET}${YELLOW} $ipdel"
echo -e "${WHITE}${BOLD}  EXPIRED ON :${RESET}${YELLOW} $exp4"
garis
banner "SCRIPT BY $nama"
}
clear
checking_sc
rm -r /root/izin &> /dev/null
if [ ! -s /etc/apigh ]; then
  echo "Token GITHUB tidak ditemukan."
  echo "Jika Anda tidak memiliki token, tekan Enter untuk membiarkannya kosong."
  read -p "Masukkan token Github Anda: " input_token

  if [ -n "$input_token" ]; then
    echo "$input_token" > /etc/apigh
    export GH="$input_token"
  else
    echo "Tidak ada token dimasukkan, tidak dapat melanjutkan"
	exit 1
  fi
else
  GH=$(< /etc/apigh)
  export GH
  export REPO="https://github.com/kertasbaru/izin/"
fi

garis
center "$(print_rainbow "WELCOME TO REGISTER IPVPS")"
garis
register
garis
echo -e " $YELLOW 1.$RESET ${WHITE}${BOLD}ADD IP VPS "$RESET     
echo -e " $YELLOW 2.$RESET ${WHITE}${BOLD}DELETE IP VPS"$RESET
echo -e " $YELLOW 3.$RESET ${WHITE}${BOLD}RENEW IP VPS"$RESET
echo -e " $YELLOW 4.$RESET ${WHITE}${BOLD}Back To menu"$RESET
garis
while true; do
echo ""
read -p " Select From Options [1 - 4 or x] : " menu
case $menu in
		1 | 01) add-ip ; break;;
		2 | 02) del-ip ; break;;
		3 | 03) renew-ip ; break;;
		4 | 04 | x | X) menu ; break;;
        *) 	
			tput cuu 1 && tput el 
			tput cuu 1 && tput el 
            echo -e "\nInput tidak valid! Silakan coba lagi."
            sleep 2
			tput cuu 1 && tput el  
            ;;
    esac
	tput cuu 1 && tput el  
    read -p "Tekan Enter untuk kembali ke menu..."
    tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done