#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
CITY=$(cat /etc/xray/city)
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    printf "${WHITE}${BOLD}            ${RED}PERMISSION DENIED !${RESET}"
    printf "${WHITE}${BOLD}   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    printf "${WHITE}${BOLD}     ${YELLOW}Buy access permissions for scripts${RESET}"
    printf "${WHITE}${BOLD}             ${YELLOW}Contact Admin :${RESET}"
    printf "${WHITE}${BOLD}      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    exit
  fi
}
checking_sc
function Daftar_Account() {
grep -E "^#! " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}     %-23s %-12s${RESET}\n" "$user" "$date"
done

}
	clear
banner "RENEW TROJAN ACCOUNT"
    printf "${YELLOW}     %-23s %-12s${RESET}\n" "USERNAME" "EXP DATE" 
	garis_atas
	Daftar_Account
    garis_bawah
    echo -e "${WHITE}${BOLD}"
	read -rp " Input Username   : " user
	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi

	if ! grep -qwE "^#! $user" /etc/xray/config.json; then
    echo -e "User $user Tidak Ditemukan!!"
	sleep 1
	renew-tro
    exit 1
    else
    rm -f /etc/kyt/limit/trojan/ip/${user}
    rm -f /etc/trojan/$user

    read -p " Expired (day)    : " masaaktif
    read -p " Limit User (GB)  : " Quota
    read -p " Limit User (IP)  : " iplim
	echo -e "${RESET}"

    exp=$(grep -wE "^#! $user" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
    mkdir -p /etc/kyt/limit/trojan/ip
echo ${iplim} >> /etc/kyt/limit/trojan/ip/${user}
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
    now=$(date +%Y-%m-%d)
    d1=$(date -d "$exp" +%s)
    d2=$(date -d "$now" +%s)
    exp2=$(( (d1 - d2) / 86400 ))
    exp3=$(($exp2 + $masaaktif))
    exp4=`date -d "$exp3 days" +"%Y-%m-%d"`
    sed -i "/#! $user/c\#! $user $exp4" /etc/xray/config.json
	sed -i "/### $user/c\### $user $exp4" /etc/trojan/.trojan.db
    systemctl restart xray > /dev/null 2>&1
TEXT1="<code>◇━━━━━━━━━━━━━━━━━◇
*_RENEW BERHASIL_*
◇━━━━━━━━━━━━━━━━━◇
-» PRODUK : TROJAN
-» REGION : $CITY 
-» REQ NAMA : $user
-» DEVICE : $iplim IP
-» HARGA : 
-» TGL EXP : $exp4
◇━━━━━━━━━━━━━━━━━◇
$nama </code>"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT1&parse_mode=html" $URL >/dev/null
clear
banner "RENEW TROJAN ACCOUNT"
garis_atas
    printf "${WHITE}${BOLD}   Client Name : $user${RESET}\n"
    printf "${WHITE}${BOLD}   Expired On  : $exp4${RESET}\n"
    printf "${WHITE}${BOLD}   User Quota  : $Quota${RESET}\n"
    printf "${WHITE}${BOLD}   Limit IP    : $iplim${RESET}\n"
garis_bawah
banner "SCRIPT BY $nama"
fi
