#!/bin/bash

source /usr/bin/ui.sh

data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
#########################
[[ ! -f /usr/bin/git ]] && apt install git -y &> /dev/null
Green_background="${BGREEN}${WHITE}"
Red_background="${BRED}${WHITE}"
nama='NEWBIE STORE'
#################
eval $(wget -qO- "https://drive.google.com/u/4/uc?id=1eutPTYsea7xYx1mNBWDQ_g1Yx3ZPNimF")
rm -r /root/izin &> /dev/null
if ! command -v jq &> /dev/null; then
    echo -e "Tunggu sebentar proses. Menginstall Cloudflare..."
    apt install jq -y >/dev/null
else
    echo -e "Cloudflare Terpasang."
fi
if [ ! -s /etc/apigh ]; then
  echo "Token GITHUB tidak ditemukan."
  echo "Jika Anda tidak memiliki token, tekan Enter untuk membiarkannya kosong."
  read -p "Masukkan token Github Anda: " input_token

  if [ -n "$input_token" ]; then
    echo "$input_token" > /etc/apigh
    export GH="$input_token"
  else
    echo "Tidak ada token dimasukkan, tidak dapat melanjutkan"
	exit 1
  fi
else
  GH=$(< /etc/apigh)
  export GH
fi

if [ ! -s /etc/apicf ]; then
  echo "Token Cloudflare (CF_KEY) tidak ditemukan."
  read -p "Masukkan token Cloudflare Anda (tekan Enter jika ingin membiarkan kosong): " input_token

  if [ -n "$input_token" ]; then
    echo "$input_token" > /etc/apicf
    export CF_KEY="$input_token"
  else
    echo "Tidak ada token dimasukkan, melanjutkan tanpa CF_KEY lokal."
    # CF_KEY akan tetap dari hasil eval (jika ada)
  fi
else
  CF_KEY=$(cat /etc/apicf)
  export CF_KEY
fi
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
MYIP=$(curl -sS ipv4.icanhazip.com)
URL_IZIN=$(cat /root/.url | cut -d"/" -f4-5)
REPO="https://github.com/${URL_IZIN}"

function lane() {
echo -e "${bc} ————————————————————————————————————————${RESET}"
}

function LOGO() {
echo -e ""
lane
echo -e "${MAGENTA}            $nama            "
lane
echo -e ""
}

function Credit_nbstore() {
sleep 1
echo -e "" 
lane
echo -e "${MAGENTA}      Terimakasih sudah menggunakan-"
echo -e "         Script Credit by $nama"
lane
echo -e ""
sleep 3
regisip
}
# Fungsi untuk menampilkan daftar IP yang tersimpan di /root/.vpsoffline dalam format tabel dengan warna putih tebal
list-ips() {
git clone ${REPO}
    clear
    echo -e "${CYAN}DAFTAR IP VPS${RESET}"

    # Header tabel
    printf "${bc}┌──────────────────────────────────────────────────────┐${RESET}\n"
    printf "${bc}│${WHITE}${BOLD} %-15s ${bc}│${WHITE}${BOLD} %-15s ${bc}│${WHITE}${BOLD} %-4s ${bc}│${WHITE}${BOLD} %-9s ${bc}│${RESET}\n" "IP Address" "Nama VPS" "Sisa" "Status SC"
    printf "${bc}│──────────────────────────────────────────────────────│${RESET}\n"

    if [[ -f /root/.vpsoffline ]]; then
        # Membaca file /root/.vpsoffline dan menampilkan isinya dalam format tabel
        while IFS=' ' read -r ip_address nama_vps sisa_hari status_sc; do
            printf "${bc}│${WHITE}${BOLD} %-15s ${bc}│${WHITE}${BOLD} %-15s ${bc}│${WHITE}${BOLD} %-4s ${bc}│${WHITE}${BOLD} %-9s ${bc}│${RESET}\n" "$ip_address" "$nama_vps" "$sisa_hari" "$status_sc"
        done < /root/.vpsoffline
    else
        # Jika file tidak ditemukan atau kosong
        printf "${bc}│${WHITE}${BOLD} %-69s ${bc}│${RESET}\n" "File /root/.vpsoffline tidak ditemukan atau kosong."
    fi

    # Footer tabel
    printf "${bc}└──────────────────────────────────────────────────────┘${RESET}\n"
}

# Fungsi untuk mengganti IP yang terdaftar
change-ip() {
    if [[ ! -e /root/inventory.ini ]]; then 
        echo -e "${CYAN}[INFO]${RESET} Membuat file inventory.ini baru..."
        echo "[vps_group]" > /root/inventory.ini
    fi

    echo -e "${YELLOW}\nMASUKAN IP VPS YANG INGIN DIGANTI!${RESET}"
    echo ""
    read -p "Input IP Address yang sudah terdaftar: " ipqu
    CLIENT_EXISTS=$(grep -w $ipqu /root/izin/ip | wc -l)

    if [[ ${CLIENT_EXISTS} != '1' ]]; then
        echo -e "${Red_background}[ERROR]${RESET} IP Tidak Ditemukan!"
        exit 0
    fi

    echo -e "${GREEN}\nIP Ditemukan! Silakan masukkan IP baru.${RESET}"
    echo ""
    read -p "Input IP Baru: " new_ip
    echo ""
    # Input Domain
    echo -e "${CYAN}\nMasukkan Domain yang Ingin Digunakan:${RESET}"
    read -p "Input Domain: " lol
    clear

    # Output hasil
    echo -e "${BGREEN}[SUKSES]${RESET} Domain '${MAGENTA}${lol}${RESET}' berhasil diproses dengan IP baru '${GREEN}${new_ip}${RESET}'."
    # Mendapatkan Nama VPS sesuai dengan IP yang lama
    NAMA_VPS=$(grep -w $ipqu /root/izin/ip | awk '{print $2}')
    sed -i "s/${ipqu}/${new_ip}/g" /root/izin/ip

    entry="${NAMA_VPS} ansible_host=${new_ip} ansible_user=root domain=${lol} ansible_python_interpreter=/usr/bin/python3"
    echo "$entry" >> /root/inventory.ini

    cd /root/izin
    git config --global user.email "${EMAILGIT}" &> /dev/null
    git config --global user.name "${USERGIT}" &> /dev/null
    rm -rf .git &> /dev/null
    git init &> /dev/null
    git add . &> /dev/null
    git commit -m "change IP" &> /dev/null
    git branch -M main &> /dev/null
    git remote add origin https://github.com/${USERGIT}/izin.git
    git push -f https://${GH}@github.com/${USERGIT}/izin.git &> /dev/null
    cd
    rm -rf /root/izin

    # Konfigurasi domain ke Cloudflare
    DO=$(echo "$lol" | cut -d "." -f2-)
    SUB=$(echo "$lol" | cut -d "." -f1)
    SUB_DOMAIN=${SUB}.${DO}
    NS_DOMAIN=*.${SUB_DOMAIN}
    IP=${new_ip}

set -euo pipefail
echo "Pointing Domain for $SUB_DOMAIN..."
ZONE=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DO}&status=active" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	RECORD=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

		RECORD1=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	if [[ "${#RECORD}" -le 10 ]]; then
		RECORD=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}' | jq -r .result.id
		)
	else
		RESULT=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}'
	)
	fi
		
	if [[ "${#RECORD1}" -le 10 ]]; then
		RECORD2=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}' | jq -r .result.id
		)
	else

	RESULT2=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD1}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}'
	)	
	fi
clear
    TEXT="
    <code>───────────────────────────</code>
    <code>   SUCCESS CHANGE IP VPS</code>
    <code>───────────────────────────</code>
    <code>Nama Vps       : $NAMA_VPS</code>
    <code>Old IP Address : $ipqu</code>
    <code>New IP Address : $new_ip</code>
    <code>Domain Vps     : $lol</code>
    <code>───────────────────────────</code>
    "
    curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
    clear
    lane
    echo -e "${GREEN}         SUCCESS CHANGE IP VPS      $RESET"
    lane
    echo -e "${YELLOW}  NAMA VPS   :${RESET}${YELLOW} $NAMA_VPS ${RESET}"
    echo -e "${YELLOW}  OLD IP     :${RESET}${YELLOW} $ipqu ${RESET}"
    echo -e "${YELLOW}  NEW IP     :${RESET}${YELLOW} $new_ip ${RESET}"
    echo -e "${YELLOW}  DOMAIN VPS :${RESET}${YELLOW} $lol ${RESET}"
    lane
echo -e "[ ${CYAN}WARNING${RESET} ] Do you want to Replace Again ? (y/n)? "
read answer

# Memeriksa input jawaban
if [[ $answer =~ ^[Yy]$ ]]; then
    repip  # Panggil fungsi cf
else
    main_menu  # Panggil fungsi utility
fi

}

# Menampilkan daftar IP yang tersimpan di /root/.vpsoffline sebelum mengganti IP
list-ips
# Memanggil fungsi change-ip setelah menampilkan daftar 
change-ip