#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc

# // System Information
domain=$(cat /etc/xray/domain)
WKT=$(curl -s ipinfo.io/timezone)
IPVPS=$(curl -s ipv4.icanhazip.com)
tram=$(free -m | awk 'NR==2 {print $2}')
swap=$(free -m | awk 'NR==4 {print $2}')
freq=$(awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo)
cores=$(awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo)
cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo)
knr=$( uname -r )

clear
# // Exporting IP Address
export IP=$( curl -s https://ipinfo.io/ip/ )
clear
# // SSH
ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
openvpn_service="$(systemctl show openvpn.service --no-page)"
oovpn=$(echo "${openvpn_service}" | grep 'ActiveState=' | cut -f2 -d=)
dropbear_status=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#noobz_service=$(systemctl status noobzvpns | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
fail2ban_service=$(/etc/init.d/fail2ban status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
cron_service=$(systemctl  status cron | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn1=$(systemctl status badvpn1 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn2=$(systemctl status badvpn2 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
badvpn3=$(systemctl status badvpn3 | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
Iptables=$(systemctl status netfilter-persistent | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
RClocal=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Autorebot=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
UdpSSH=$(systemctl status udp-custom | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
openssh=$( systemctl status ssh | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
clear

if [[ $openssh == "running" ]]; then
    status_openssh="${GREEN}[ON]$RESET"
else
    status_openssh="${RED}[OFF]${RESET} "
fi

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${GREEN}[ON]$RESET"
else
    status_ws_epro="${RED}[OFF]${RESET} "
fi

# // Trojan Proxy
ss=$( systemctl status xray | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ss == "running" ]]; then
    status_ss="${GREEN}[ON]$RESET"
else
    status_ss="${RED}[OFF]${RESET} "
fi

# // NGINX
nginx=$( /etc/init.d/nginx status | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $nginx == "running" ]]; then
    status_nginx="${GREEN}[ON]$RESET"
else
    status_nginx="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE IPTABLES
if [[ $Iptables == "exited" ]]; then
    status_galo="${GREEN}[ON]$RESET"
else
    status_galo="${RED}[OFF]${RESET}"
fi

# STATUS SERVICE  SSH 
if [[ $ssh_service == "running" ]]; then 
   status_ssh="${GREEN}[ON]$RESET"
else
   status_ssh="${RED}[OFF]${RESET} "
fi

# STATUS NOOBZVPNS SSH 
if [[ $noobz_service == "running" ]]; then 
   status_noobz="${GREEN}[ON]$RESET"
else
   status_noobz="${RED}[OFF]${RESET} "
fi

# STATUS OHP SSH
#if [[ $ohr == "running" ]]; then 
 #  sohr="${GREEN}[ON]${RESET}${RESET}"
#else
 #  sohr="${RED}[OFF]${RESET} ${RESET}"
#fi

# STATUS SERVICE OPENVPN
if [[ $oovpn == "active" ]]; then
  status_openvpn="${GREEN}[ON]$RESET"
else
  status_openvpn="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE DROPBEAR
if [[ $dropbear_status == "running" ]]; then 
   status_beruangjatuh="${GREEN}[ON]$RESET"
else
   status_beruangjatuh="${RED}[OFF]${RESET} ${RESET}"
fi

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then 
   status_haproxy="${GREEN}[ON]$RESET"
else
   status_haproxy="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE  SQUID 
#if [[ $squid_service == "running" ]]; then 
  # status_squid="${GREEN}[ON]${RESET} ( No Etror )"
#else
  # status_squid="${RED}[OFF]${RESET} "
#fi

# STATUS SERVICE  FAIL2BAN 
if [[ $fail2ban_service == "running" ]]; then 
   status_fail2ban="${GREEN}[ON]$RESET"
else
   status_fail2ban="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE  CRONS 
if [[ $cron_service == "running" ]]; then 
   status_cron="${GREEN}[ON]$RESET"
else
   status_cron="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE  BADVPN 1
if [[ $badvpn1 == "running" ]]; then 
   status_udp1="${GREEN}[ON]$RESET"
else
   status_udp1="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE  BADVPN 2
if [[ $badvpn2 == "running" ]]; then 
   status_udp2="${GREEN}[ON]$RESET"
else
   status_udp2="${RED}[OFF]${RESET} "
fi

# STATUS SERVICE  BADVPN 3
if [[ $badvpn3 == "running" ]]; then 
   status_udp3="${GREEN}[ON]$RESET"
else
   status_udp3="${RED}[OFF]${RESET} "
fi

if [[ $RClocal == "exited" ]]; then
    status_galoo="${GREEN}[ON]$RESET"
else
    status_galoo="${RED}[OFF]${RESET}"
fi

if [[ $Autorebot == "exited" ]]; then
    status_galooo="${GREEN}[ON]$RESET"
else
    status_galooo="${RED}[OFF]${RESET}"
fi

# STATUS SERVICE  SSH UDP 
if [[ $UdpSSH == "running" ]]; then 
   status_udp="${GREEN}[ON]$RESET"
else
   status_udp="${RED}[OFF]${RESET} "
fi

# // Running Function 
clear

banner "SHOW ALL SERVCIE SYSTEM"
garis_atas
echo -e "  ${WHITE}${BOLD}Service SSH / TUN                 ${CYAN}=$RESET $status_ssh"
echo -e "  ${WHITE}${BOLD}Service SSH UDP                   ${CYAN}=$RESET $status_udp"
#echo -e " ${WHITE}${BOLD}Service SSH NOOBZVPNS             ${CYAN}=$RESET $status_noobz"
echo -e "  ${WHITE}${BOLD}Service OpenVPN SSL               ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service OpenVPN WS-SSL            ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service OpenVPN UDP               ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service OpenVPN TCP               ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service OHP SSH                   ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service OHP Dropbear              ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service OHP OpenVPN               ${CYAN}=$RESET $status_openvpn"
echo -e "  ${WHITE}${BOLD}Service WS ePRO                   ${CYAN}=$RESET $status_ws_epro"
echo -e "  ${WHITE}${BOLD}Service BadVPN 7100               ${CYAN}=$RESET $status_udp1"
echo -e "  ${WHITE}${BOLD}Service BadVPN 7200               ${CYAN}=$RESET $status_udp2"
echo -e "  ${WHITE}${BOLD}Service BadVPN 7300               ${CYAN}=$RESET $status_udp3"
echo -e "  ${WHITE}${BOLD}Service Dropbear                  ${CYAN}=$RESET $status_beruangjatuh"
echo -e "  ${WHITE}${BOLD}Service Haproxy                   ${CYAN}=$RESET $status_haproxy"
echo -e "  ${WHITE}${BOLD}Service Crons                     ${CYAN}=$RESET $status_cron"
echo -e "  ${WHITE}${BOLD}Service Nginx Webserver           ${CYAN}=$RESET $status_nginx"
echo -e "  ${WHITE}${BOLD}Service Xray Vmess WS TLS         ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Vmess WS Non TLS     ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Vmess gRPC           ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Vless WS TLS         ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Vless WS Non TLS     ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Vless gRPC           ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Trojan WS            ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Trojan Non WS        ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Trojan gRPC          ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Shadowsocks WS       ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Shadowsocks Non WS   ${CYAN}=$RESET $status_ss"
echo -e "  ${WHITE}${BOLD}Service Xray Shadowsocks gRPC     ${CYAN}=$RESET $status_ss"
garis_bawah
banner "SCRIPT BY $nama"
