#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
clear

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    printf "${WHITE}${BOLD}            ${RED}PERMISSION DENIED !${RESET}"
    printf "${WHITE}${BOLD}   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    printf "${WHITE}${BOLD}     ${YELLOW}Buy access permissions for scripts${RESET}"
    printf "${WHITE}${BOLD}             ${YELLOW}Contact Admin :${RESET}"
    printf "${WHITE}${BOLD}      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    exit
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear
banner "TRIAL VLESS ACCOUNT"
echo ""
read -p "  Minutes      :    " waktu_ekspirasi_menit
if ! [[ $waktu_ekspirasi_menit =~ ^[0-9]+$ ]]; then
    echo -e "${ERROR} Masukan harus berupa angka."
	trial-vle
    exit 1
fi
masaaktif=0
Quota=1
iplimit=10
user=Trial-VL`</dev/urandom tr -dc 0-9 | head -c3`
clear
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
clear
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&host=${domain}&encryption=none&type=ws&sni=${domain}#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&security=none&host=${domain}&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"
cat >/var/www/html/vless-$user.txt <<-END

======================
     $nama
======================
# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
    grpc-service-name: vless-grpc

======================
Link Akun Vless 
======================
Link TLS      : 
${vlesslink1}
======================
Link none TLS : 
${vlesslink2}
======================
Link GRPC     : 
${vlesslink3}
======================
Aktif Selama  : $waktu_ekspirasi_menit Minutes

END

if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vless/ip
echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
fi
echo "sed -i '/$user/d' /etc/xray/config.json" | at now + $waktu_ekspirasi_menit minutes &> /dev/null
waktu_restart=$((waktu_ekspirasi_menit + 1))
echo "systemctl restart xray" | at now + $waktu_restart minutes &> /dev/null
clear
     
curl -s -o /dev/null -X POST "https://api.telegram.org/bot$KEY/sendMessage" \
-F chat_id="$CHATID" \
-F parse_mode="HTML" \
-F text="◇━━━━━━━━━━━━━━━━━◇
      XRAY/VLESS
◇━━━━━━━━━━━━━━━━━◇
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : <code>${uuid}</code>
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vless-grpc
◇━━━━━━━━━━━━━━━━━◇
LINK TLS  
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink1}</code>
◇━━━━━━━━━━━━━━━━━◇
LINK NTLS 
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink2}</code>
◇━━━━━━━━━━━━━━━━━◇
LINK GPRC 
◇━━━━━━━━━━━━━━━━━◇
<code>${vlesslink3}</code>
◇━━━━━━━━━━━━━━━━━◇
Format OpenClash : https://${domain}:81/vless-$user.txt
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama  : $waktu_ekspirasi_menit Minutes
◇━━━━━━━━━━━━━━━━━◇
"

function Details_Account() {
printf "${WHITE}${BOLD} Remarks     : ${user}${RESET}\n"
printf "${WHITE}${BOLD} Domain      : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota  : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} port TLS    : 443,900,8443${RESET}\n"
printf "${WHITE}${BOLD} Location    : $CITY${RESET}\n"
printf "${WHITE}${BOLD} ISP         : $ISP${RESET}\n"
printf "${WHITE}${BOLD} Port WS     : 80,8080,8880,2086,2082${RESET}\n"
printf "${WHITE}${BOLD} Key         : ${uuid}${RESET}\n"
printf "${WHITE}${BOLD} Encryption  : none${RESET}\n"
printf "${WHITE}${BOLD} Path TLS    : /vless${RESET}\n"
printf "${WHITE}${BOLD} ServiceName : vless-grpc${RESET}\n"
}

function Link_Json() {
garis
printf "${WHITE}${BOLD} Link TLS   : ${vlesslink1}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link NTLS  : ${vlesslink2}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link GRPC  : ${vlesslink3}${RESET}\n"
garis
printf "${WHITE}${BOLD} OpenClash  : https://${domain}:81/vless-$user.txt${RESET}\n"
garis
}

function Details_Expiry() {
printf "${YELLOW} Expiry     : $waktu_ekspirasi_menit Minutes ${RESET}\n"
}

banner "TRIAL VLESS ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"
