#!/bin/bash

source /usr/bin/ui.sh

nama=$(cat /etc/xray/username)
clear

# Getting
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "${GREEN}loading...${RESET}"
clear
# Valid Script
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
   echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${RESET}"
    echo -e "   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    echo -e "     ${YELLOW}Buy access permissions for scripts${RESET}"
    echo -e "             ${YELLOW}Contact Admin :${RESET}"
    echo -e "      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    exit
  fi
}
checking_sc
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
clear
IP=$(curl -sS ipv4.icanhazip.com)
Login=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=1
iplimit=99
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
clear
banner "MEMBER SSH"
center "$(printf "${YELLOW}[ SET MINUTES ]${RESET}")"
garis
echo -e "${WHITE}${BOLD}"
read -p " Minutes : " pup
echo userdel ${Login} | at now + $pup minutes &> /dev/null
echo -e "${RESET}"
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>Your Premium VPN Details</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>IP Address    =</code> <code>$IP</code>
<code>Hostname      =</code> <code>$domain</code>
<code>Username      =</code> <code>$Login</code>
<code>Password      =</code> <code>$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>OpenSSH       = 22
Dropbear      = 443, 109, 143
SSL/TLS       = 400-900
SSH WS TLS    = 443
SSH WS NTLS   = 80, 8080, 8081-9999
OVPN WS NTLS  = 80, 8080, 8880
OVPN WS TLS   = 443
BadVPN UDP    = 7100,7200,7300</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>SSH WEBSOCKET    : </code><code>$domain:80@$Login:$Pass</code>
<code>SSH SSL          : </code><code>$domain:443@$Login:$Pass</code>
<code>SSH UDP          : </code><code>$domain:1-65535@$Login:$Pass</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Ovpn Download : https://$domain:81/
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Save Link Account: https://$domain:81/ssh-$Login.txt
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Berakhir Pada  : $pup Menit
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo ""
mkdir -p /etc/ssh

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
echo ""
cat > /var/www/html/ssh-$Login.txt <<-END
======================
Format SSH OVPN Account
======================
Username         : $Login
Password         : $Pass
Berakhir Pada  : $pup Menit
======================
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
======================
Payload : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
======================
OVPN Download : https://$domain:81/
======================

END
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf] "

clear
# Port Account Detail
function Ssh_Details(){
garis
center "$(print_rainbow "[ SSH OPENVPN ]")"
garis
echo -e "${WHITE}${BOLD}"
echo -e " Remark   : ${Login}"
echo -e " pasword  : ${Pass}"
echo -e " limit ip : ${iplimit}"
echo -e " Domain   : ${domain}"
echo -e " Port Udp : 1-65535 "
echo -e " Port WS  : 80,8880,2082,8080"
echo -e " Port Tls : 443,8443 "
echo -e " OpenSSH  : 22,143 "
echo -e " OVPN Tls : 443 "
echo -e " Ovpn UdP : 2200 "
echo -e " Ovpn Tcp : 443 "
echo -e "${RESET}"
garis
}
function Copy_Faste(){
echo -e "${WHITE}${BOLD} Port 80     : $domain:80@$Login:$Pass ${RESET}"
echo -e "${WHITE}${BOLD} Port 443    : $domain:443@$Login:$Pass ${RESET}"
echo -e "${WHITE}${BOLD} Udp Custom  : $domain:1-65535@$Login:$Pass${RESET}"
echo -e "${WHITE}${BOLD} OpenVpn     : https://$domain:81/ "
echo -e "${WHITE}${BOLD} Account     : https://$domain:81/ssh-$Login.txt "
}
# Payload Detail 
function Payload_Details(){
garis
echo -e "${WHITE}${BOLD}"
echo " Payload WS    : ${PAYLOADWS}"
garis
echo " Payload Tls   : ${PAYLOADTLS}"
garis
echo " Payload Hnced : ${PAYLOADHANCED}"
echo -e "${RESET}"
garis
}

# Expired Account
function Expiry_Account(){
echo -e "${RED} Expiry in  : ${pup} "
garis
}
Ssh_Details
Copy_Faste
Payload_Details
Expiry_Account
banner "SCRIPT BY $nama"