#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
clear

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1

  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear
banner "TRIAL TROJAN ACCOUNT"
echo ""
read -p "  Minutes      :    " waktu_ekspirasi_menit
if ! [[ $waktu_ekspirasi_menit =~ ^[0-9]+$ ]]; then
    echo -e "${ERROR} Masukan harus berupa angka."
	trial-tro
    exit 1
fi
masaaktif=0
Quota=1
iplimit=10
user=Trial-TR`</dev/urandom tr -dc 0-9 | head -c3`
clear
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
# Link Trojan Akun
systemctl restart xray
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=bug.com#${user}"
trojanlink="trojan://${uuid}@bugkamu.com:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

cat >/var/www/html/trojan-$user.txt <<-END
======================
     $nama 
======================
# Format Trojan GO/WS

- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

# Format Trojan gRPC

- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

======================
Link Akun Trojan 
======================
Link TLS          : 
${trojanlink}
======================
Link NTLS          : 
${trojanlink2}
======================
Link GRPC        : 
${trojanlink1}
======================
Aktif Selama  : $waktu_ekspirasi_menit Minutes
END
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/trojan/ip
echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
echo "sed -i '/$user/d' /etc/xray/config.json" | at now + $waktu_ekspirasi_menit minutes &> /dev/null
waktu_restart=$((waktu_ekspirasi_menit + 1))
echo "systemctl restart xray" | at now + $waktu_restart minutes &> /dev/null
clear
curl -s -o /dev/null -X POST "https://api.telegram.org/bot$KEY/sendMessage" \
-F chat_id="$CHATID" \
-F parse_mode="HTML" \
-F text="◇━━━━━━━━━━━━━━━━━◇
      XRAY/TROJAN
◇━━━━━━━━━━━━━━━━━◇
Remarks   : ${user}
Domain    : ${domain}
Limit Quota : ${Quota} GB
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : <code>${uuid}</code>
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : trojan-grpc
◇━━━━━━━━━━━━━━━━━◇
TROJAN TLS
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink}</code>
◇━━━━━━━━━━━━━━━━━◇
TROJAN NTLS
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink2}</code>
◇━━━━━━━━━━━━━━━━━◇
TROJAN gRPC
◇━━━━━━━━━━━━━━━━━◇
<code>${trojanlink1}</code>
◇━━━━━━━━━━━━━━━━━◇
Format OpenClash : https://${domain}:81/trojan-$user.txt
◇━━━━━━━━━━━━━━━━━◇
Aktif Selama  : $waktu_ekspirasi_menit Minutes
◇━━━━━━━━━━━━━━━━━◇
"

function Details_Account() {
printf "${WHITE}${BOLD} Remarks      : ${user}${RESET}\n"
printf "${WHITE}${BOLD} Host/IP      : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota   : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} User IP      : ${iplimit} IP${RESET}\n"
printf "${WHITE}${BOLD} ISP          : $ISP${RESET}\n"
printf "${WHITE}${BOLD} Port TLS     : 443${RESET}\n" 
printf "${WHITE}${BOLD} port  WS     : 80,8880,8080${RESET}\n"
printf "${WHITE}${BOLD} Key          : ${uuid}${RESET}\n" 
printf "${WHITE}${BOLD} Path         : /trojan-ws${RESET}\n" 
printf "${WHITE}${BOLD} ServiceName  : trojan-grpc${RESET}\n"
}

function Link_Json() {
garis 
printf "${WHITE}${BOLD} Link WS      : ${trojanlink}${RESET}\n" 
garis 
printf "${WHITE}${BOLD} Link TLS     : ${trojanlink2}${RESET}\n" 
garis 
printf "${WHITE}${BOLD} Link GRPC    : ${trojanlink1}${RESET}\n" 
garis 
printf "${WHITE}${BOLD} OpenClash    : https://${domain}:81/trojan-$user.txt${RESET}\n" 
garis
}

function Details_Expiry() {
printf "${RED} Expiry       : $waktu_ekspirasi_menit Minutes ${RESET}\n"

}
banner "TRIAL TROJAN ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"
