#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
command -v at >/dev/null 2>&1 || apt install -y at >/dev/null 2>&1
clear
garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

clear
#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
clear

# // Get Bot
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e "${BGREEN}          404 NOT FOUND AUTOSCRIPT          ${RESET}"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    echo -e ""
    printf "${WHITE}${BOLD}            ${RED}PERMISSION DENIED !${RESET}"
    printf "${WHITE}${BOLD}   ${YELLOW}Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
    printf "${WHITE}${BOLD}     ${YELLOW}Buy access permissions for scripts${RESET}"
    printf "${WHITE}${BOLD}             ${YELLOW}Contact Admin :${RESET}"
    printf "${WHITE}${BOLD}      ${GREEN}WhatsApp${RESET} wa.me/6282326322300"
    echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
    exit
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear
banner "TRIAL VMESS ACCOUNT"
echo ""
read -p "  Minutes      :    " waktu_ekspirasi_menit
if ! [[ $waktu_ekspirasi_menit =~ ^[0-9]+$ ]]; then
    echo -e "${ERROR} Masukan harus berupa angka."
	trial-vme
    exit 1
fi
masaaktif=0
Quota=1
iplimit=10
user=Trial-VM`</dev/urandom tr -dc 0-9 | head -c3`
clear 
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgprc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
asu=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
ask=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF`
grpc=`cat<<EOF
      {
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF`
vmess_base641=$( base64 -w 0 <<< $vmess_json1)
vmess_base642=$( base64 -w 0 <<< $vmess_json2)
vmess_base643=$( base64 -w 0 <<< $vmess_json3)
vmesslink1="vmess://$(echo $asu | base64 -w 0)"
vmesslink2="vmess://$(echo $ask | base64 -w 0)"
vmesslink3="vmess://$(echo $grpc | base64 -w 0)"

cat >/var/www/html/vmess-$user.txt <<-END

======================
  $nama
======================
# Format Vmess WS TLS

- name: Vmess-$user-WS TLS
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess WS Non TLS

- name: Vmess-$user-WS Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess gRPC

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

======================
 Link Akun Vmess                   
======================
Link TLS         : 
${vmesslink1}
======================
Link none TLS    : 
${vmesslink2}
======================
Link GRPC        : 
${vmesslink3}
======================
Aktif Selama   : $waktu_ekspirasi_menit Menit
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
======================
END
if [ ! -e /etc/vmess ]; then
  mkdir -p /etc/vmess
fi

if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/vmess/ip
echo -e "$iplimit" > /etc/kyt/limit/vmess/ip/$user
else
echo > /dev/null
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vmess/${user}
fi
echo "sed -i '/$user/d' /etc/xray/config.json" | at now + $waktu_ekspirasi_menit minutes &> /dev/null
waktu_restart=$((waktu_ekspirasi_menit + 1))
echo "systemctl restart xray" | at now + $waktu_restart minutes &> /dev/null
clear
     
TEXT="<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>      XRAY/VMESS</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Remarks   : ${user}
Domain    : ${domain}
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : <code>${uuid}</code>
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vmess-grpc
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code> VMESS WS TLS</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>${vmesslink1}</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code> VMESS WS NO TLS</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>${vmesslink2}</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code> VMESS gRPC</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
<code>${vmesslink3}</code>
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Format OpenClash : https://${domain}:81/vmess-$user.txt
<code>◇━━━━━━━━━━━━━━━━━◇</code>
Aktif Selama   : $waktu_ekspirasi_menit Menit
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
<code>◇━━━━━━━━━━━━━━━━━◇</code>
"

curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null

clear
function Details_Account() {
printf "${WHITE}${BOLD} Remarks       : ${user}${RESET}\n"
printf "${WHITE}${BOLD} Domain        : ${domain}${RESET}\n"
printf "${WHITE}${BOLD} User Quota    : ${Quota} GB${RESET}\n"
printf "${WHITE}${BOLD} Port TLS      : 443-900${RESET}\n"
printf "${WHITE}${BOLD} Port  WS      : 80,8080,8880,2082,2095${RESET}\n"
printf "${WHITE}${BOLD} Location      : $CITY${RESET}\n"
printf "${WHITE}${BOLD} ISP           : $ISP${RESET}\n"
printf "${WHITE}${BOLD} Key           : ${uuid}${RESET}\n"
printf "${WHITE}${BOLD} AlterId       : 0${RESET}\n"
printf "${WHITE}${BOLD} Security      : auto${RESET}\n"
printf "${WHITE}${BOLD} Network       : ws${RESET}\n"
printf "${WHITE}${BOLD} Path          : /vmess${RESET}\n"
printf "${WHITE}${BOLD} Dynamic Path  : https://bugmu.com/vmess${RESET}\n"
printf "${WHITE}${BOLD} ServiceName   : vmess-grpc${RESET}\n"
}

function Link_Json() {
garis
printf "${WHITE}${BOLD} Link TLS      : ${vmesslink1}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link  WS      : ${vmesslink2}${RESET}\n"
garis
printf "${WHITE}${BOLD} Link GRPC     : ${vmesslink3}${RESET}\n"
garis
printf "${WHITE}${BOLD} OpenClash     : https://${domain}:81/vmess-$user.txt${RESET}\n"
garis

}

function Details_Expiry() {
printf "${RED} Expiry in     : $waktu_ekspirasi_menit Minutes ${RESET}\n"

}
banner "TRIAL VMESS ACCOUNT"
Details_Account
Link_Json
Details_Expiry
banner "SCRIPT BY $nama"
