#!/bin/bash

source /usr/bin/ui.sh

# //====================================================
# //  Newbie Store - Copy 2024
# //====================================================
# //  System Request : DEB 9-12 / UBUNTU 18-24
# //  Author         : Kurniawan Setiadi
# //  Develop        : Newbie Store
# //  email          : Newbiestore09@gmail.com
# //  telegram       : https://t.me/newbie_store24
# //====================================================
clear
nama=$(cat /etc/xray/username)
CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
domain=$(cat /etc/xray/domain)

garis_bawah(){
print_rainbow " └──────────────────────────────────────────────┘"
}
garis_atas(){
print_rainbow " ┌──────────────────────────────────────────────┐"
}

function send_log(){
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="
<code>────────────────────
<b>⚠️ NOTIF UNLOCK XRAY ⚠️</b>
────────────────────
Username  : $user
Expaired  : ${exp}
Status    : UNLOCKED
────────────────────</code>
"
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
}
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/kertasbaru/izin/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep -wE $ipsaya | awk '{print $3}')

  if [[ "$useexp" == "Lifetime" ]]; then
    # Jika useexp adalah "Lifetime", anggap tetap aktif

    return
  fi
  date_list_epoch=$(date -d "$date_list" +%s)
  useexp_epoch=$(date -d "$useexp" +%s 2>/dev/null)

  if [[ $? -ne 0 || $date_list_epoch -gt $useexp_epoch ]]; then
    # Tanggal sekarang lebih besar dari tanggal expired, atau format salah
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e "${BRED}${BOLD} ⚠️       AKSES DI TOLAK         ⚠️ ${RESET}"
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
echo -e ""
echo -e "        ${RED}❌ SCRIPT LOCKED ❌${RESET}"
echo -e ""
echo -e "  ${YELLOW}🔒 Your VPS${RESET} $ipsaya ${YELLOW}Has been Banned${RESET}"
echo -e ""
echo -e "  ${RED}⚠️  Masa Aktif Sudah Habis ⚠️${RESET}"
echo -e "  ${YELLOW}💡 Beli izin resmi hanya dari Admin!${RESET}"
echo -e ""
echo -e "  ${GREEN}📞 Contact Admin:${RESET}"
echo -e "  ${CYAN}🌍 Telegram: https://t.me/WuzzSTORE${RESET}"
echo -e "  ${CYAN}📱 WhatsApp: https://wa.me/6287760204418${RESET}"
echo -e ""
echo -e "${YELLOW}────────────────────────────────────────────${RESET}"
exit 1
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
function Daftar_Account() {
grep -E "^### " "/etc/xray/.lock.db" | cut -d ' ' -f 2-3 | sort | uniq | while read -r user date; do
    printf "${WHITE}${BOLD}    %-25s %-12s${RESET}\n" "$user" "$date"
done
}
banner "UNLOCK VMESS ACCOUNT"
printf "${WHITE}${BOLD}     %-25s %-12s${RESET}\n" "USERNAME" "EXP DATE"
garis_atas
Daftar_Account
garis_bawah
  echo -e "${WHITE}${BOLD}"
  read -rp " Username         : " -e user
  	echo -e "${RESET}"
  	if [[ -z "$user" || "$user" == "exit" ]]; then
    m-xray
    exit
	fi
  if grep -i -w -q "$user" /etc/xray/config.json; then
    clear
banner "UNLOCK VMESS ACCOUNT"
    garis
    echo ""
    echo -e "${RED} Name Salah: Username sudah terdaftar!! ${RESET}"
    echo ""
    garis
banner "SCRIPT BY $nama"
  fi
clear
	uuid=$(grep -E "^###" "/etc/xray/.lock.db" |  grep -wE "${user}" | cut -d " " -f 4 | sort | uniq | tail -n1)
	exp=$(grep -E "^###" "/etc/xray/.lock.db" |  grep -wE "${user}" | cut -d " " -f 3 | sort | uniq | tail -n1)
if [ -z $uuid ]; then
garis
center "$(printf "${RED}[ Unlock Account Failed! ]${RESET}\n")"
garis  
echo -e ""
echo -e "   UUID Tidak Valid"
echo -e ""
garis
read -n 1 -s -r -p "Press any key to back"
m-xray
exit 1
	else
    sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
    sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i "/^### $user/d" /etc/xray/.lock.db
    systemctl restart xray > /dev/null 2>&1
    clear
banner "UNLOCK VMESS ACCOUNT"
  garis_atas
  printf "${WHITE}${BOLD}  Username : $user ${RESET}\n"
  printf "${WHITE}${BOLD}  Exp Date : $exp ${RESET}\n"
  printf "${WHITE}${BOLD}  Status   : Unlocked ${RESET}\n"
  garis_bawah
  send_log
banner "SCRIPT BY $nama"
    fi  