export GH=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
export KEY=8027285741:AAF0sCbk1pTtpiDKNQHPPzCMUzixxwziTcw
export KEYBK=8427936329:AAG3znggoUmm_FQPqlqnJnd6Eh8ubb9vQvg
export CHATID=6686272246
export IZIN=https://raw.githubusercontent.com/kertasbaru/izin/main/ip
export REPO=https://raw.githubusercontent.com/kertasbaru/os/main/
export USERGIT=kertasbaru
export EMAILGIT=wuzzstore04@gmail.com
export REPIZIN=https://github.com/kertasbaru/izin.git
export UPIZIN=https://github.com/kertasbaru/izin
export CF_KEY=f7b3dccdddad29233872697f6f01a4bfc3474
export CF_ID=wuzzstore04@gmail.com
export DOMAINAUTO=vpn-wuzzstore.my.id
